### ISSUE TITLE
Casting Position Bug

### ISSUE THREAD

**Issue by kyeme** [HerculesWS/Hercules#1001] opened 2015-12-21 17:16 UTC
Whenever I click on a cell and I cast a self -skill before stepping on that certain cell my charactter goes back to the cell where I was.

Video: https://youtu.be/PVRk7I59dmw

Bug tracker: http://herc.ws/board/index.php?app=tracker&showissue=7255

**Comment by Playtester** [comment] 2016-01-27 10:47
I kind of have implemented the functionality needed for this with stepaction already...

```c
	// Remember the skill request from the client while walking to the next cell
	if(src->type == BL_PC && ud->walktimer != INVALID_TIMER && !battle->check_range(src, target, range-1)) {
		ud->stepaction = true;
		ud->target_to = target_id;
		ud->stepskill_id = skill_id;
		ud->stepskill_lv = skill_lv;
		return 0; // Attacking will be handled by unit_walktoxy_timer in this case
	}
```
But I didn't want it to apply unless when absolutely necessary, because of the complex timer mechanics that are involved with that, so I only did when you cast while the target is not in range (battle->check_range). If you removed that check it would always apply. Of course for self skills, the target is always in range. 

Problem is that unlike using a skill outside skill range where you can be sure that the client itself will make sure you stop one cell later, if you cast a self spell while moving, you will continue walking after reaching the next cell, so if your latency is high, you will still see yourself moving to the next cell...

I tried to solve this by sending the client a move packet saying that the path was shortened, but the client ignored it. =/

Alternatively, one could simply remove the fixpos when stopping because of casting, but might create position lag. With fixpos it looks funny but at least you can tell on which cell the server considers you to be on.

**Comment by stealth62** [comment] 2016-03-25 08:27
Hello :) any update for this?

**Comment by Playtester** [comment] 2016-03-25 12:27
For rAthena I decided to keep it as it is. On official servers you are also pulled back to the previous cell but it doesn't send a fixpos packet so it just causes position lag. I rather have the real position show.

**Comment by stealth62** [comment] 2016-03-25 13:55
I see. Sir @Playtester  can you help me how to do that not sending a fixpos packet?

**Comment by stealth62** [comment] 2016-03-25 15:13
In my testing Sir @Playtester  in unit.c
```
int unit_stop_walking(struct block_list *bl,int type)
```
i comment the line to disable it
```
clif_fixpos(bl); // i dont know if commenting this line is safe
```
then my character didn't back to  the cell where I was. Like you said it causes position lag on high latency server. In my testing commenting the line i dont know if its safe or if you have any method sir please help. Thank you very much.

**Comment by Playtester** [comment] 2016-03-25 17:03
It's better if you go to unit.c --> unit_skilluse_id2

And change:
```c
	if(!ud->state.running) // Need TK_RUN or WUGDASH handler to be done before that, see bugreport:6026
		unit_stop_walking(src, 1); // Even though this is not how official works but this will do the trick. bugreport:6829
```

To:
```c
	if(!ud->state.running) // Need TK_RUN or WUGDASH handler to be done before that, see bugreport:6026
		unit_stop_walking(src, 0); // Even though this is not how official works but this will do the trick. bugreport:6829
```

Then it doesn't affect other situations.

**Comment by stealth62** [comment] 2016-03-25 17:34
Thank you very much sir @Playtester  it works for me. this is what im looking for long time ago :)

**Comment by kyeme** [comment] 2016-03-26 03:06
I think it would be better to revert the previous fix of http://herc.ws/board/tracker/issue-6829-casting-skills/?gopid=15207#entry15207 then let's just try to make another way to fix the bug... So as not to encounter 'Casting Position Bug'

**Comment by Kenpachi2k13** [comment] 2020-05-07 02:51
I can confirm that Aegis either pushes you back to the previous cell, but shows the coordinate of next cell when using /where or does **not** push you back the previous cell but shows the coordinate of previous cell when using /where.
In both cases the character's position is corrupted.
I agree with @Playtester that keeping the character's position uncorrupted is more important, so there's nothing to "fix" here.

**Closed by Kenpachi2k13** 2020-05-07 02:51 UTC
Labels: component:core, type:bug
