### ISSUE TITLE
min_npc_vendchat_distance setting shouldn't apply to invisible NPC sprite

### ISSUE THREAD

**Issue by emistry** [HerculesWS/Hercules#834] opened 2015-10-28 12:28 UTC
https://github.com/HerculesWS/Hercules/blob/master/conf/battle/player.conf#L149
```
// Minimum distance a vending/chat room must be from a NPC in order to be placed
// Default: 3 (0: disabled).
min_npc_vendchat_distance: 3
```
I think this option shouldn't apply to any "invisible" NPC.

This settings implemented to avoid players vending block the NPC visibility. I think it shouldn't apply to any NPC sprite that is invisible, 

__Example Sprites__ :
* -1
* HIDDEN_NPC (111)
* HIDDEN_WARP_NPC (139)

or at least it shouldn't apply to NPC with sprite of -1

**Comment by MishimaHaruna** [comment] 2015-10-28 13:12
Are there actual use cases for NPCs with view ID `-1`, but placed on a map (as opposed to floating NPCs)?

As for `HIDDEN_NPC`, while it doesn't have a sprite, it still shows a clickable bubble, and as such, I think the distance setting should apply to it (making it otherwise very hard to click, just like the case where a sprite is visible)

I'm not familiar with the in-game appearance of `HIDDEN_WARP_NPC`, so I can't say anything about that one.

**Comment by emistry** [comment] 2015-10-28 13:29
owh ya the `HIDDEN_NPC` does have the clickable bubble.
but `HIDDEN_WARP_NPC` doesn't have the clickable bubble.
the NPC with `-1` as sprite work exactly the same like `HIDDEN_WARP_NPC`.

I think it should apply to `HIDDEN_WARP_NPC` or `-1` then.

the `-1` previously vastly used in floating npc, but sometime users do use it to create an invisible sprite, which exactly the same with `HIDDEN_WARP_NPC`.

**Comment by AnnieRuru** [comment] 2015-10-28 17:15
@emistry , if you mean your vending script, why not just add a few lines in the source for it ?
just like my koe script also has a few line patch, completely custom stuff

I think we shouldn't do this kind of change
just because 1 person script doesn't work, we shouldn't change the whole root system

for your edit: HIDDEN_WARP_NPC is used in official script
changing the behavior might cause official script bug

EDIT: yeah, I fixed your script again
http://herc.ws/board/topic/4509-vendor-control-rewrite/

**Comment by hemagx** [comment] 2015-10-28 17:22
actually i remember in official anything that hidden are just fine to do something near them, need test tho, if i got some time later.

**Comment by emistry** [comment] 2015-10-29 05:02
@AnnieRuru  ==''  it's not about the vending script, not even related to any of my current or previous scripts. 

What I trying to express is the logical usage for these settings. What's the point to restrict the NPC to vending near them when these NPC isnt even visible.
The settings was implemented to avoid vendor block the NPCs which make players hard to click on it or see it. That's the main reason why the settings was implemented.

But when it come to invisible NPCs what's the point of restricting it ?? 

It's like you're telling the player 
> "Hey I created an invisible NPC here, nobody found it so far and  guess what ? you're so lucky that you are the first person who found it through the vending action... congratulations."

The main idea for `Hidden` NPC was to hide it from NPC, then it should be can't discover by players.

**Comment by kyeme** [comment] 2015-10-29 05:30
Regarding on HIDDEN_NPC(111)
On official you cant use pub or vend
![1](https://cloud.githubusercontent.com/assets/4656578/10810912/1401289e-7e41-11e5-8703-e30fd67521fb.jpg)

Aegis: npc "alberta_in" "Letter" HIDDEN_NPC 18 102 4 0 0

**Comment by emistry** [comment] 2015-10-29 05:58
@kyeme  Maybe can help to check on these location ??
http://pastebin.com/raw.php?i=25kGh6zM

**Comment by kyeme** [comment] 2015-10-29 06:13
@emistry 
Here is the result:
![2](https://cloud.githubusercontent.com/assets/4656578/10811463/24d2c258-7e47-11e5-8d3d-f3f1a13d079a.jpg)
I can't use chatroom

aldebaran,140,130,0	script	#jmAldebaran Clock Tower	HIDDEN_WARP_NPC,3,3,{

**Comment by AnnieRuru** [comment] 2015-10-29 06:30
@emistry 
although its pointless, but this is an official behavior so we shouldn't fix it
we can always use source modification if our custom script doesn't match the official behavior

and confirmed this is an official behavior, so we should mark this as 'work as intended' ?

or you want a battle config to allow players to vend near hidden npcs ?
well, I think you are good enough to write on your own and make a pull request, I guess

**Comment by AnnieRuru** [comment] 2015-10-29 09:15
I just can't seem to get my head off from this issue
so I'm doing it
#837

**Comment by MishimaHaruna** [comment] 2015-11-18 14:12
Merged the pull request~

**Closed by MishimaHaruna** 2015-11-18 14:12 UTC
Labels: component:core, status:inprogress, type:enhancement
