### ISSUE TITLE
Vending Bug in Client 2015-05-13aRagexe.exe

### ISSUE THREAD

**Issue by Triedge** [HerculesWS/Hercules#604] opened 2015-07-21 02:16 UTC
When a player puts a shop Vending, this is a failure in the list of items to sell.

If you put 2 or more items in the shop vending, this will only show one or no object. There are also occasions in showing a red apple with a huge price.

**Comment by MishimaHaruna** [comment] 2015-08-29 15:45
duplicate of #611

**Closed by MishimaHaruna** 2015-08-29 15:45 UTC
