### ISSUE TITLE
Guild Position Change 

### ISSUE THREAD

**Issue by tlacson7** [HerculesWS/Hercules#927] opened 2015-12-10 13:20 UTC
im having issue when changing guild position name of Guild Master. Im using pre-renewal 

--- failed assertion --------------------------------------------
(12/10/2015 21:14:28) [ Error ] : guild.c:1118: 'idx > 0 && idx < (16+10*6)' in function `guild_position_changed'

**Comment by Jedzkie** [comment] 2015-12-10 13:22
did you change you max guild capacity?

**Comment by tlacson7** [comment] 2015-12-10 13:25
// Update this max as necessary. 86 is the value needed for Expanded Super Novice.
#define MAX_SKILL_TREE 86
#define DEFAULT_WALK_SPEED 150
#define MIN_WALK_SPEED 20 /* below 20 clips animation */
#define MAX_WALK_SPEED 1000
#define MAX_STORAGE 600
#define MAX_GUILD_STORAGE 600
#define MAX_PARTY 12
#define BASE_GUILD_SIZE 16               // Base guild members (without GD_EXTENSION)
#define MAX_GUILD (BASE_GUILD_SIZE+10*6) // Increased max guild members +6 per 1 extension levels [Lupus]
#define MAX_GUILDPOSITION 20             // Increased max guild positions to accomodate for all members [Valaris] (removed) [PoW]
#define MAX_GUILDEXPULSION 32
#define MAX_GUILDALLIANCE 16
#define MAX_GUILDSKILL 15                // Increased max guild skills because of new skills [Sara-chan]
#define MAX_GUILDLEVEL 50
#define MAX_GUARDIANS 8                  // Local max per castle. [Skotlex]
#define MAX_QUEST_OBJECTIVES 3           // Max quest objectives for a quest
#define MAX_START_ITEMS 32               // Max number of items allowed to be given to a char whenever it's created. [mkbu95]

**Comment by Jedzkie** [comment] 2015-12-10 13:29
so from +16 you made it to +106?

Then, you forgot these line to change also.

https://github.com/HerculesWS/Hercules/blob/master/src/char/int_guild.c#L840

**Comment by tlacson7** [comment] 2015-12-10 13:34
Sorry Jedzkie but its a normal setting, i just got typo on the about values.  this is the value

// Update this max as necessary. 86 is the value needed for Expanded Super Novice.
#define MAX_SKILL_TREE 86
#define DEFAULT_WALK_SPEED 150
#define MIN_WALK_SPEED 20 /* below 20 clips animation */
#define MAX_WALK_SPEED 1000
#define MAX_STORAGE 600
#define MAX_GUILD_STORAGE 600
#define MAX_PARTY 12
#define BASE_GUILD_SIZE 16               // Base guild members (without GD_EXTENSION)
#define MAX_GUILD (BASE_GUILD_SIZE+10*6) // Increased max guild members +6 per 1 extension levels [Lupus]

**Comment by tlacson7** [comment] 2015-12-10 13:34
ohhh why i cant do asterisk here?
10*6 test

**Comment by dastgir** [comment] 2015-12-10 13:46
Caused by https://github.com/HerculesWS/Hercules/commit/55ead23717432966098853438c7e29de32e369fe

@4144

**Comment by 4144** [comment] 2015-12-10 14:08
Fixed in latest git

**Comment by dastgir** [comment] 2015-12-10 14:08
https://github.com/HerculesWS/Hercules/commit/5829747a48294da0cd3af4a60ab6aedc471b07a3

**Closed by dastgir** 2015-12-10 14:08 UTC
Labels: status:confirmed, type:bug
