### ISSUE TITLE
Over weight 50% and 90% notification

### ISSUE THREAD

**Issue by kyeme** [HerculesWS/Hercules#563] opened 2015-06-20 15:07 UTC
On official server, the Over Weight notification appears in the chatbox every time the player changes map.
![ow notice every loadmap](https://cloud.githubusercontent.com/assets/4656578/8267824/fdf2747e-17a0-11e5-9e23-1b3472a925c1.jpg)

Source: iRO

**Comment by hemagx** [comment] 2015-06-20 17:17
i confirm, tested on my own test box.

**Comment by kyeme** [comment] 2015-12-13 04:07
@hemagx thanks

Up~

**Comment by MishimaHaruna** [comment] 2015-12-20 16:08
If this is ever implemented, please make it optional. It's one of the many things that are like this because of how Aegis works, rather than because they were intended, or are of any use.

**Comment by hemagx** [comment] 2015-12-20 16:25
it's not big deal to add one more check and send one more packet, but why ? just why ? to emulate aegis bugs ? i confirmed it's true, but I'm totally against emulate this stuff.

**Comment by Kenpachi2k13** [comment] 2020-01-27 04:12
@MishimaHaruna Should this be implemented or not?
I agree with @hemagx, but since it's official behaviour there's an argument for implementing it, too.

**Comment by dastgirp** [comment] 2020-01-28 13:11
We already have status icons to indicate if player is overweight, if someone wants to implement, have it optional.

**Comment by hemagx** [comment] 2020-01-28 13:16
after 5 years I will say it again, why? do you have better argument than it's official behavior?
Does it break gameplay? no.
Does it affect a skill, battle, or UX? no.
Does it add any extra benefits? no.
Don't emulate a clear bug or code limitation in aegis, period.
I will close this issue and let it die.

**Closed by hemagx** 2020-01-28 13:16 UTC
Labels: component:other, status:confirmed, type:enhancement

**Comment by kyeme** [comment] 2020-04-23 05:56
Notification is one of the main focus of the players in game that's why we should implement a notification on the chatbox about the effects of being overweight wherever they go so they can prepare. The Over Weight icon is not enough because sometimes the players won't notice it if he/she has a lot of buffs.
![12345](https://user-images.githubusercontent.com/4656578/80064208-1bf09280-856a-11ea-9266-81614982c8a5.jpg)

**Comment by Kenpachi2k13** [comment] 2020-04-24 19:43
@hemagx 
In my opinion @kyeme's argument is reasonable.
