### ISSUE TITLE
Map Crash

### ISSUE THREAD

**Issue by tlacson7** [HerculesWS/Hercules#1832] opened 2017-08-27 14:44 UTC
-  [x ] I have not modified the source prior to reproducing this issue.
-  [ x] I am using the latest version of Hercules.
-  [ x] I am aware that this report will be closed or deleted if it becomes obvious that I am stating the false.

I just find my server down, and i got this crash log, i think its something about Geffenia Warp.

`#0  pop_stack (st=0x7ffff626e544, start=0, end=0) at script.c:3745
        stack = 0x0
        data = <optimized out>
        i = <optimized out>
        end = 0
        start = 0
        st = 0x7ffff626e544
#1  0x000000000059fc1e in run_func (st=0x7ffff626e544) at script.c:4428
        data = <optimized out>
        i = <optimized out>
        start_sp = <optimized out>
        func = 27
        end_sp = <optimized out>
        st = 0x7ffff626e544
#2  0x00000000005a0e90 in run_script_main (st=0x7ffff626e544) at script.c:4668
        c = <optimized out>
        cmdcount = 654894
        gotocount = 2015
        sd = <optimized out>
        stack = 0x7ffff097d62c
        nd = <optimized out>
#3  0x0000000000526862 in npc_event_sub (sd=<optimized out>,
    ev=<optimized out>, eventname=<optimized out>) at npc.c:863
---Type <return> to continue, or q <return> to quit---

        eventname = <optimized out>
        ev = <optimized out>
        sd = <optimized out>
#4  0x0000000000529067 in npc_ontouch2_event (sd=0x386a680, nd=<optimized out>)
    at npc.c:190
        name = "Geffenia Warp::OnTouch\000\000\000\332\377\377\377\177\000\000\060\334\377\377\377\177\000\000_\334\377\377\377\177\000\000a\334\377"
        nd = <optimized out>
        sd = 0x386a680
#5  0x00000000005262d7 in npc_enable_sub (bl=0x386a680,
    ap=ap@entry=0x7fffffffda88) at npc.c:222
        nd = 0x7fffeed0bb5c
        ap = 0x7fffffffda88
        bl = 0x386a680
#6  0x00000000004fa988 in bl_vforeach (
    func=func@entry=0x526240 <npc_enable_sub>, blockcount=blockcount@entry=0,
    max=max@entry=2147483647, args=args@entry=0x7fffffffdaf8) at map.c:535
        argscopy = {{gp_offset = 48, fp_offset = 48,
            overflow_arg_area = 0x7fffffffdc40,
            reg_save_area = 0x7fffffffdb70}}
        i = 0
        returnCount = 0
#7  0x0000000000504c40 in map_vforeachinarea (func=0x526240 <npc_enable_sub>,
---Type <return> to continue, or q <return> to quit---

    m=<optimized out>, x0=<optimized out>, y0=<optimized out>,
    x1=<optimized out>, y1=<optimized out>, type=1, ap=0x7fffffffdb58)
    at map.c:998
        returnCount = 0
        blockcount = 0
        apcopy = {{gp_offset = 48, fp_offset = 48,
            overflow_arg_area = 0x7fffffffdc38,
            reg_save_area = 0x7fffffffdb70}}
#8  0x00000000004fa28c in map_foreachinarea (func=<optimized out>,
    m=<optimized out>, x0=<optimized out>, y0=<optimized out>,
    x1=<optimized out>, y1=<optimized out>, type=1) at map.c:1024
        returnCount = -165223100
        ap = {{gp_offset = 48, fp_offset = 48,
            overflow_arg_area = 0x7fffffffdc38,
            reg_save_area = 0x7fffffffdb70}}
#9  0x000000000051d2f6 in npc_enable (name=0x7ffff6302e5b "Geffenia Warp",
    flag=<optimized out>) at npc.c:267
        nd = 0x7fffeed0bb5c
#10 0x000000000056cfda in buildin_enablenpc (st=<optimized out>)
    at script.c:11898
        str = <optimized out>
#11 0x000000000059fbfa in run_func (st=0x7ffff6271fe4) at script.c:4415
        data = 0x7fffefb658d4
---Type <return> to continue, or q <return> to quit---

       i = <optimized out>
        start_sp = <optimized out>
        func = 158
        end_sp = <optimized out>
        st = 0x7ffff6271fe4
#12 0x00000000005a0e90 in run_script_main (st=0x7ffff6271fe4) at script.c:4668
        c = <optimized out>
        cmdcount = 655353
        gotocount = 2048
        sd = <optimized out>
        stack = 0x7ffff097f02c
        nd = <optimized out>
#13 0x00000000005263f4 in npc_event_do (name=<optimized out>) at npc.c:443
        ev = <optimized out>
        name = <optimized out>
#14 0x000000000056b411 in buildin_donpcevent (st=0x7ffff62728ac)
    at script.c:11005
        event = 0x7fffef259233 "Geffenia Warp::OnEnable"
#15 0x000000000059fbfa in run_func (st=0x7ffff62728ac) at script.c:4415
        data = 0x7fffefb64054
        i = <optimized out>
        start_sp = <optimized out>
        func = 136
---Type <return> to continue, or q <return> to quit---
       end_sp = <optimized out>
        st = 0x7ffff62728ac
#16 0x00000000005a0e90 in run_script_main (st=0x7ffff62728ac) at script.c:4668
        c = <optimized out>
        cmdcount = 655309
        gotocount = 2047
        sd = <optimized out>
        stack = 0x7ffff097f45c
        nd = <optimized out>
#17 0x000000000051dc57 in npc_scriptcont (sd=0x2467040, id=<optimized out>,
    closing=<optimized out>) at npc.c:1364
        target = <optimized out>
        __func__ = "npc_scriptcont"
#18 0x00000000004cad2f in clif_parse (fd=140) at clif.c:19876
        parse_cmd_func = <optimized out>
        cmd = 184
        packet_len = 7
        sd = 0x2467040
        pnum = 0
#19 0x000000000064a0be in do_sockets (next=<optimized out>) at socket.c:1034
        rfd = {fds_bits = {0, 0, 4096, 0 <repeats 13 times>}}
        timeout = {tv_sec = 0, tv_usec = 30201}
        ret = 0
---Type <return> to continue, or q <return> to quit---
`

**Comment by Asheraf** [comment] 2017-08-27 15:50
This seems like a duplication of #568 @HerculesWS/developers

**Comment by MishimaHaruna** [comment] 2017-08-27 18:25
Yes I believe so. It looks as if an autotrading merchant was in the spot where the Geffenia warp appears when it was enabled.

Closing this in favor of the other issue.

Duplicate of #568

**Closed by MishimaHaruna** 2017-08-27 18:25 UTC
