### ISSUE TITLE
*rodex_sendmail_acc script command doesn't work as intended

### ISSUE THREAD

**Issue by AnnieRuru** [HerculesWS/Hercules#2024] opened 2018-04-24 17:33 UTC
### Issue Prelude

-  [x] I have not modified the source prior to reproducing this issue.
-  [x] I am using the latest version of Hercules.
-  [x] I am aware that this report will be closed or deleted if it becomes obvious that I am stating the false.

### Description
Rodex mail system doesn't work as intended when using *rodex_sendmail_acc script command

### Current Behavior
it behave just the same as a normal *rodex_sendmail script command

### Expected Behavior
it should send the mail to the whole account, where any character in the account can retrieve the mail

### Steps To Reproduce The Issue
```
-	script	sjfskjfd	FAKE_NPC,{
OnInit:
	// with message "Hello World, How are You?", 1000 Zenies and 5 Red Potions attached
	rodex_sendmail_acc(
		2000000, "Rodex Test", "Rodex Test3", "Hello World, How are You?",
		1000,
		Red_Potion, 5
	);
}
```
1. get this script in -> which is [2nd sample from doc](https://github.com/HerculesWS/Hercules/blob/stable/doc/sample/npc_rodex.txt#L22)
notice that I change from 150000 into 2000000, because it should do this way
2. yes I don't get the mail using my main char, which is account_id 2000000

**Now here has some interesting things happening**
`SELECT * FROM rodex_mail;`
run this query, and I can see the 2000000 is set inside `receiver_id` field
it should be inside `receiver_accountid` field

so I change the `receiver_id` field into 0, and `receiver_accountid` into 2000000
when I login my main char,
there is an incoming mail icon indicating that I HAVE a new mail, but when I open it, its empty

so I change again the `receiver_id` field into 1, and `receiver_accountid` into 2000000
now I can open this mail from any character within the account **<-- which is intended behavior**

### Branch(es):
- [x] master

### Hercules rev. hash/commit: & Operating System
>[Info]: Hercules 32-bit for Windows
[Info]: Git revision (src): 'efeb386abc51baffa561f32d7d3b30868af767cd'
[Info]: Git revision (scripts): 'efeb386abc51baffa561f32d7d3b30868af767cd'
[Info]: OS version: 'Windows 7 Ultimate Service Pack 1 (build 7601) [x86]'
[Info]: CPU: 'x86 CPU, Family 6, Model 23, Stepping 10 [2]'
[Info]: Compiled with Microsoft Visual C++ 2015 (v1900)
[Info]: Compile Flags: N/A

PS: actually if I don't follow this guidelines, I could describe the behavior better in linear form ...

**Comment by guilherme-gm** [comment] 2018-04-24 20:53
I think `strcmp` is missing `rodex_sedmail_acc` here:
https://github.com/HerculesWS/Hercules/blob/stable/src/map/script.c#L23717

**Comment by AnnieRuru** [comment] 2018-04-25 00:38
conf\map\battle\features,conf ?
```
	// Allow usage of "Account Mail" box in RoDEX?
	// Requires: 2016-03-16aRagexeRE or later
	// This is disabled in client-side in some client versions
	// Disabled by default
	rodex_use_accountmail: true
```
how this things work ? I'm using 2017-05-17 hexed client

**Comment by AnnieRuru** [comment] 2018-04-25 00:49
yup I change that line into
```
if (!strcmp(script->getfuncname(st), "rodex_sendmail_acc2") || !strcmp(script->getfuncname(st), "rodex_sendmail_acc"))
```
now I got a notification `You've got a new mail` in the client
but the same, I click the notification icon, open it and its empty

because the problem is `receiver_id` still has to set to 1 to actually get a mail to read

**Comment by guilherme-gm** [comment] 2018-04-25 15:27
Account Mail is the old name of the "Announcement" tab, they changed it at some point. But some clients simple disable this tab (2017-04-26 for example), when you click the tab it doesn't work,

**Comment by Asheraf** [comment] 2018-04-25 15:31
@guilherme-gm announcements tab disabled by default in most RE clients, its active only in Ragexe and Ragexe_zero

**Comment by Asheraf** [comment] 2018-04-25 18:56
This works as intended (besides the missing check for `rodex_sendmail_acc`), the account mails tab is disables client side in RE clients.. if someone want to use it then use another version of the client or patch your client to enable it.

@guilherme-gm as for moving them to char tab that will work but personally i believe this should be fixed client side and we keep the server side work as official.

**Comment by guilherme-gm** [comment] 2018-04-25 20:12
I see, I thought announcements could be being used for something else (so it would made sense to change it), but if not, I think it's okay, just add more info to docs?

**Comment by AnnieRuru** [comment] 2018-04-26 02:32
@Asheraf how about ... add a battle config so that other client version also can use account mails ?
after all ... I see rathena didn't even have account mail field

**Closed** 2018-07-01 23:41 UTC
Labels: component:core, component:core:scriptengine, status:confirmed, type:bug
