### ISSUE TITLE
Issue with pre-increment operator

### ISSUE THREAD

**Issue by mekolat** [HerculesWS/Hercules#1710] opened 2017-04-24 14:47 UTC
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

[//]: # (Note: Lines beginning with syntax such as this one, are comments and will not be visible in your report!)

### Issue Prelude

[//]: # (Please complete these mandatory steps and check the following boxes by putting an `x` inside the brackets _before_ filing your issue)

-  [X] I have not modified the source prior to reproducing this issue.
-  [X] I am using the latest version of Hercules.
-  [X] I am aware that this report will be closed or deleted if it becomes obvious that I am stating the false.

### Description
For some reason the pre-increment operator triggers an error when passed as argument to a buildin, without parentheses.

### Current Behavior
* `++@foo;`
    * works just fine when used alone
* `debugmes ++@foo;`
    * triggers `[Error]: Cannot modify a variable which has the same name as a function or label.`
* `debugmes(++@foo);`
    * does not trigger the error
* `debugmes (++@foo);`
    * does not trigger the error

**UPDATE:** also affects the `if` statement, see https://github.com/HerculesWS/Hercules/issues/1710#issuecomment-296765182

### Steps to reproduce
1. Place `debugmes ++@foo;` anywhere in any script.

- - -
Here I'm using `debugmes` but pretty much any buildin triggers the error. The variable name or scope is also irrelevant, even random variables like `.@lnslkmsfsl3435mk` triggers the error. I haven't found any issue with the post-increment operator.

**Comment by 4144** [comment] 2017-04-24 15:07
As i know any function calls without brackets is legacy syntax.
This mean use always () and will be never error in increment.

**Comment by mekolat** [comment] 2017-04-24 15:15
@4144 yes I know that, but the old syntax is not yet deprecated so it should still work as expected.

**Comment by mekolat** [comment] 2017-04-24 17:43
Found another bug with pre-increment:

* `if (condition == true) ++@foo;`
    * triggers the error
* `if (condition == true) { ++@foo; }`
    * does not trigger the error

**Comment by Asheraf** [comment] 2017-04-24 18:29
@mekolat the second issue already reported in #705

**Comment by mekolat** [comment] 2017-04-24 18:34
@Asheraf ok thanks, feel free to mask as duplicate

**Comment by dastgir** [comment] 2017-06-13 07:39
duplicate of #705

**Closed by dastgir** 2017-06-13 07:39 UTC
Labels: component:core:scriptengine, severity:3-medium, status:confirmed, type:bug
