### ISSUE TITLE
Critical Explosion not working correctly

### ISSUE THREAD

**Issue by Svald** [HerculesWS/Hercules#2636] opened 2020-02-21 22:02 UTC
**Describe the bug**
The Fury/Critical Explosion skill doesn't work with the latest Hercules. Although the animation and visual effects ar﻿e visible when used, the character brings up a merchant's cart and doesn't seem to enter the Fury state (sp regen doesn't stop, spirit spheres are consumed, etc...).

**To Reproduce**
1. Get 5 spirit spheres on a monk/champion
2. Use Critical Explosion

**Expected behavior**
1. The character should enter the Fury state when this skill is used, and stop regenerating sp among other things. 
2. A cart should not appear.

**Screenshots**
[.gif of a champion reproducing the issue](https://s4.gifyu.com/images/fury_bug.gif)

**System specs (please complete the following information):**
- Hercules v2020.02.09
- Hercules is running on Raspbian, using its latest gcc
-  Client [20120410aRagexe](http://nemo.herc.ws/downloads/2012-04-10aRagexe/) on Windows 10 64-bits
 - Mode: Pre-renewal, but also tested on Renewal with same results
 - Packet version: 20120410

**Plugins used or source modifications**
None.

**Additional context**
 - The cart that pops up isn't merely a visual effect, you can actually open it up, store things in it, and walk around as a champ with the cart on your back
- When the Fury skill is used, the plain gray cart is the one that appears, but when you enter a warp with it, it changes to another kind of cart
- Notice from the .gif that items introduced in the first cart don't appear after Fury is used at first, but they do when I cross the warp ﻿

**Comment by hemagx** [comment] 2020-02-21 23:44
This issue is confirmed to be due to our last release (Feb 2020)

**Comment by tlacson7** [comment] 2020-02-22 04:24
We need emergency fix for this. Thanks dev

**Comment by Vaans** [comment] 2020-02-23 16:12
Yes, this is highly critical.  make the job unusable, please devs hope can be fixed quickly.

**Closed** 2020-03-09 11:47 UTC
Labels: component:core, component:mechanics:skills, severity:5-critical, status:confirmed
