### ISSUE TITLE
++.@i throw error using with while loop

### ISSUE THREAD

**Issue by AnnieRuru** [HerculesWS/Hercules#912] opened 2015-12-06 21:02 UTC
@MishimaHaruna 
`Always use the prefix form of increment/decrement operators where possible.`, right ?

when I want to find a value in the array, I love to use this trick
```
prontera,155,185,5	script	ksdjfsf	1_F_MARIA,{
	input .@id;
	while ( .mvpcardid[.@i] != .@id && .@i < .mvpcards ) .@i++;
	if ( .@i < .mvpcards )
		mes "yes it is a mvp card";
	else
		mes "nope, it isn't";
	close;
OnInit:
	.mvpcards = query_sql("select item_db.id from item_db right join mob_db on item_db.id = mob_db.dropcardid where mexp > 0 and type = 6 group by name_japanese;", .mvpcardid);
	end;
}
```
however, when I change that line into this
`while ( .mvpcardid[.@i] != .@id && .@i < .mvpcards ) ++.@i;`
the server throw error on me
```
[Error]: script error in file 'npc/zzz.txt' line 3 column 56
    parse_simpleexpr: unexpected character
     1: {
     2:         input .@id;
*    3:         while ( .mvpcardid[.@i] != .@id && .@i < .mvpcards ) ++.@i;
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
     4:         if ( .@i < .mvpcards )
     5:                 mes "yes it is a mvp card";
     6:         else
```
is this normal, or script engine bug ?

**Comment by AnnieRuru** [comment] 2015-12-06 21:05
erm, I just test like this
`while ( .mvpcardid[.@i] != .@id && .@i < .mvpcards ) { ++.@i; }` it don't throw error and it worked o.o

**Comment by MishimaHaruna** [comment] 2015-12-06 21:46
Yep, that's a known issue with the parser. Prefix increment and decrement operators are parsed incorrectly if the curly brackets are missing

**Comment by AnnieRuru** [comment] 2015-12-06 22:05
so this is actually a script engine bug, I see
I guess for the time being, I have to put curly bracket

```
prontera,155,185,5	script	ksdjfsf	1_F_MARIA,{
	if ( .@i == 1 ) ++.@i;
	end;
}
```
```
[Error]: script error in file 'npc/zzz.txt' line 2 column 19
    parse_simpleexpr: unexpected character
     1: {
*    2:         if ( .@i == 1 ) ++.@i;
        ~~~~~~~~~~~~~~~~~~~~~~~~~^
     3:         end;
     4: }
```
LOL
I guess this really has to fix

**Comment by MishimaHaruna** [comment] 2016-03-15 01:49
Marking as duplicate of #705

**Closed by MishimaHaruna** 2016-03-15 01:49 UTC
Labels: component:core:scriptengine, status:confirmed, type:bug
