### ISSUE TITLE
Warning at grfio.c when compiling on Windows

### ISSUE THREAD

**Issue by EPuncker** [HerculesWS/Hercules#2955] opened 2021-02-20 01:30 UTC
**Describe the bug**
There is a warning popping out on MSVC several times ([on this line](https://github.com/HerculesWS/Hercules/blob/stable/src/common/grfio.c#L514)):

`\src\common\grfio.c(514,31): warning C4244: 'function': conversion from 'int64' to 'long', possible loss of data`

**Screenshots**
![2021-02-19 22_27_59-Hercules-16 - Microsoft Visual Studio](https://user-images.githubusercontent.com/4684880/108578555-c1e36980-7301-11eb-9b3b-b9ff6fcf713a.png)

**System specs (please complete the following information):**
 - OS: Windows 10 x64 latest
 - Hercules Version: latest
 - Mode: N/A
 - Packet version: N/A
 - Client type: N/A

**Additional context**
Release/Win32 build

**Comment by MrKeiKun** [comment] 2021-02-21 02:03
i just updated to latest herc on my local machine
```
Warning	C4244	'function': conversion from 'int64' to 'long', possible loss of data	login-server	C:\Users\Kei\Desktop\HerculesWS\src\common\grfio.c	514	
Warning	C26451	Arithmetic overflow: Using operator '+' on a 4 byte value and then casting the result to a 8 byte value. Cast the value to the wider type before calling operator '+' to avoid overflow (io.2).	char-server	C:\Users\Kei\Desktop\HerculesWS\src\common\grfio.c	671	
Warning	C26451	Arithmetic overflow: Using operator '+' on a 4 byte value and then casting the result to a 8 byte value. Cast the value to the wider type before calling operator '+' to avoid overflow (io.2).	char-server	C:\Users\Kei\Desktop\HerculesWS\src\common\grfio.c	740	
Warning	C6054	String 'w2' might not be zero-terminated.	char-server	C:\Users\Kei\Desktop\HerculesWS\src\common\grfio.c	786	
Warning	C6054	String 'w1' might not be zero-terminated.	char-server	C:\Users\Kei\Desktop\HerculesWS\src\common\grfio.c	935	
Warning	C4244	'function': conversion from 'int64' to 'long', possible loss of data	map-server	C:\Users\Kei\Desktop\HerculesWS\src\common\grfio.c	514	
Warning	C4244	'function': conversion from 'int64' to 'long', possible loss of data	char-server	C:\Users\Kei\Desktop\HerculesWS\src\common\grfio.c	514	
```

**Comment by Asheraf** [comment] 2021-02-21 12:45
duplicate of #2935

**Closed by Asheraf** 2021-02-21 12:45 UTC
