### ISSUE TITLE
Improve changesex/changecharsex implementation

### ISSUE THREAD

**Issue by MrKeiKun** [HerculesWS/Hercules#2789] opened 2020-07-01 17:07 UTC
**Describe the bug**
Regular changesex thru `@changesex` using 2018 client gives similar result like #985 .

**To Reproduce**
1. Character is currently Job: 4020, which is Clown.
2. Enter `@changesex`
3. Login again

**System specs (please complete the following information):**
 - OS: Centos 8
 - Hercules Version: v2020.05.31+1
 - Mode: Pre-Renewal
 - Packet version: 20180418
 - Client type: RE

**Comment by MrKeiKun** [comment] 2020-07-01 17:16
If someone might tell me because i used the wrong ACMD, but in the first place whythe existence of two ACMD which does same thing but handle two different methods when emulator can only handles one at the time. Either old one which handle sex via `login` table and the newer one which is under `char` table which requires client >= 20141022

**Comment by Kenpachi2k13** [comment] 2020-07-06 11:13
Confirmed.
This happens because the SQL query in `char_change_sex_sub()` does not update the gender. (Resetting the robe view sprite ID is missing, too.):
```c
	if (SQL_ERROR == SQL->Query(inter->sql_handle, "UPDATE `%s` SET `class`='%d', `weapon`='0', `shield`='0', "
				"`head_top`='0', `head_mid`='0', `head_bottom`='0' WHERE `char_id`='%d'",
				char_db, class, char_id))
```

`@changecharsex` works because the gender is updated in `char_changecharsex()` prior to calling `char_change_sex_sub()`.
(`@changesex` calls `char_change_sex_sub()` via `char_parse_fromlogin_changesex_reply()`.)

**Comment by MrKeiKun** [comment] 2020-07-07 01:02
> 
> 
> Confirmed.
> This happens because the SQL query in `char_change_sex_sub()` does not update the gender. (Resetting the robe view sprite ID is missing, too.):
> 
> ```c
> 	if (SQL_ERROR == SQL->Query(inter->sql_handle, "UPDATE `%s` SET `class`='%d', `weapon`='0', `shield`='0', "
> 				"`head_top`='0', `head_mid`='0', `head_bottom`='0' WHERE `char_id`='%d'",
> 				char_db, class, char_id))
> ```
> 
> `@changecharsex` works because the gender is updated in `char_changecharsex()` prior to calling `char_change_sex_sub()`.
> (`@changesex` calls `char_change_sex_sub()` via `char_parse_fromlogin_changesex_reply()`.)

shouldn't we merge both ACMD? then use `#if PACKETVER` to check client if its `>= 20141016`, then it will use @changecharsex method and if not will use the traditional method?

**Comment by Kenpachi2k13** [comment] 2020-07-07 07:36
For what reason should we disable account wide gender change when using "new" clients? :flushed:

**Comment by MrKeiKun** [comment] 2020-07-07 08:50
> 
> 
> For what reason should we disable account wide gender change when using "new" clients? 😳

not really disabled but merge both command in a single one. like the example code i gave above

**Comment by 4144** [comment] 2020-07-07 13:55
account may have one gender and char another. if merged them, then will be only one gender.

**Closed** 2020-07-27 10:20 UTC
Labels: component:core, status:confirmed, type:bug
