### ISSUE TITLE
Gentle Touch Change not applying after using.

### ISSUE THREAD

**Issue by kairu** [HerculesWS/Hercules#1591] opened 2017-02-26 16:24 UTC
You basically need to cast asura strike once and then the damage will only apply on your next skills. and switching gentle touches. will leave gentle touch changes damage until you use asura strike again.

**Comment by Emistry** [comment] 2017-03-14 02:58
Duplicate of https://github.com/HerculesWS/Hercules/issues/1629. Closing this.

**Closed by Emistry** 2017-03-14 02:58 UTC
Labels: component:mechanics:skills, status:duplicate
