### ISSUE TITLE
Renewal formulas off

### ISSUE THREAD

**Issue by Asofwar** [HerculesWS/Hercules#3134] opened 2022-04-24 18:04 UTC
**Describe the bug**
When used: //#define RENEWAL /// leave this line to enable renewal specific support such as renewal formulas You are giving the following error, please tell me how to fix it
I want to disable the renewal formulas .

**To Reproduce**
1. Go to 'renewal.h'
2. Comment //#define RENEWAL
3. Rebuild

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/7397608/164990063-e6b05762-e8bb-44af-8279-7ca01e89deec.png)
![image](https://user-images.githubusercontent.com/7397608/164990074-5b8b4261-7a59-49b9-a8ea-3577de0857d4.png)
**System specs (please complete the following information):**
 - OS: windows 11
 - Hercules Version [LAST]
 - Mode: [renewal]
 - Packet version: [Last]
 - Client type: [SAK]

**Additional context**
Add any other context about the problem here. If the bug report is about a
crash, please attach the core/stack-dump or crash-log, if any.

**Comment by MrKeiKun** [comment] 2022-04-29 10:34
Cannot reproduce this problem.

**Comment by dastgirp** [comment] 2022-05-23 11:29
Unable to reproduce, closing the issue.

Please check if there's any modifications to the server.

**Closed by dastgirp** 2022-05-23 11:29 UTC
