### ISSUE TITLE
Equipped cards are not shown in the preview menu, all appear as "null".

### ISSUE THREAD

**Issue by Likeeit** [HerculesWS/Hercules#1792] opened 2017-06-26 21:27 UTC
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

[//]: # (Note: Lines beginning with syntax such as this one, are comments and will not be visible in your report!)

### Issue Prelude

[//]: # (Please complete these mandatory steps and check the following boxes by putting an `x` inside the brackets _before_ filing your issue)

-  [x] I have not modified the source prior to reproducing this issue.
-  [x] I am using the latest version of Hercules.
-  [x] I am aware that this report will be closed or deleted if it becomes obvious that I am stating the false.

### Description
Equipped cards are not shown in the preview menu, all appear as "null".
[//]: # (Description of the problem or issue at length.)
[//]: # (Please specify any battle configuration related to the components of this issue that have been changed from the default values. This will allow quicker determination of the cause of the problem.)

### Current Behavior
All  cards appear as "null".
[//]: # (Describe at length what you noticed during your analysis.)
[//]: # (If this is a crash, post the core/stack-dump or crash-log to https://gist.github.com/)
[//]: # (If you are referencing from sources such as iROwiki or ratemyserver.net, please quote specific information rather than providing the links alone.)

### Expected Behavior
All card names should be shown instead of "null".
[//]: # (Tell us what should happen instead.)

### Steps To Reproduce The Issue

1. Click in npc.
2. Next.
3. See the menu.

**Branch(es):**
- [x] master
- [ ] other

**Hercules rev. hash/commit:** 

Git revision src:
19188.
[//]: # (Copy the first 3 lines of the login-server, char-server or map-server startup.)
[//]: # ( [Info]: Hercules 64-bit for Mac OS X )
[//]: # ( [Info]: Git revision src: 'a5918b329ca0826b04dca32ede783586403f58db' )
[//]: # ( [Info]: Git revision scripts: 'a5918b329ca0826b04dca32ede783586403f58db' )

### Operating System
Windows 10 - 64 bits.
[//]: # (Mac OS X 10.12.3 16D32 [x86_64])
[//]: # (Thank you for adhering to this process! It ensures your issue is resolved quickly and that neither your nor our time is needlessly wasted.)
[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes please create a Pull Request.)

Script:

```
prontera,155,161,5	script	Cards Remove	4_M_RACHOLD1,{
getinventorylist;
for( set .@i,0; .@i < @inventorylist_count; set .@i,.@i + 1 ){
	set .@card_count,0;
	for( set .@card,1; .@card <= 4; set .@card,.@card + 1 )
		if( getd( "@inventorylist_card"+.@card+"["+.@i+"]" ) )
			set .@card_count,.@card_count + 1;
	// @inventorylist_card1[.@i] + @inventorylist_card2[.@i] + @inventorylist_card3[.@i] + @inventorylist_card4[.@i];
	if( .@card_count && !@inventorylist_expire[.@i] ){
		set .@equip_card_count,.@equip_card_count + 1;
		set .@menu$,.@menu$ + ( ( @inventorylist_refine[.@i] )?"+"+@inventorylist_refine[.@i]:"" ) + " " + getitemname( @inventorylist_id[.@i] ) + "[^777777"+(.@card)+"  "+getitemname( getd( "@inventorylist_card1[.@i],@inventorylist_card2[.@i],@inventorylist_card3[.@i],@inventorylist_card4[.@i]"+.@card+"["+.@i+"]" ))+"^000000]" + ":";
	}else{
		set .@menu$,.@menu$ + ":";
	}
}
mes "You have "+.@equip_card_count+" equipments that have card inside.";
if( .@equip_card_count ){
	do{
		next;
		set .@i,select( .@menu$ ) - 1;
		mes "You hav selected ^0055FF"+( ( @inventorylist_refine[.@i] )?"+"+@inventorylist_refine[.@i]:"" )+" "+getitemname( @inventorylist_id[.@i] )+"^000000";
		set .@max_slot,getitemslots( @inventorylist_id[.@i] );
		for( set .@card,1; .@card <= .@max_slot; set .@card,.@card + 1 )
			mes "^777777Card "+( .@card )+" : "+getitemname( getd( "@inventorylist_card"+.@card+"["+.@i+"]" ) )+"^000000";
	}while( select( "Remove Card","Select Another" ) == 2 );
	delitem2 @inventorylist_id[.@i],1,1,@inventorylist_refine[.@i],@inventorylist_attribute[.@i],@inventorylist_card1[.@i],@inventorylist_card2[.@i],@inventorylist_card3[.@i],@inventorylist_card4[.@i];
	getitem2 @inventorylist_id[.@i],1,1,@inventorylist_refine[.@i],0,0,0,0,0;
	for( set .@card,1; .@card <= .@max_slot; set .@card,.@card + 1 )
		getitem getd( "@inventorylist_card"+.@card+"["+.@i+"]" ),1;
	mes "Done...";
}
close;
}
```

**Comment by dastgir** [comment] 2017-06-27 03:00
```
getitemname( getd( "@inventorylist_card1[.@i],@inventorylist_card2[.@i],@inventorylist_card3[.@i],@inventorylist_card4[.@i]"+.@card+"["+.@i+"]" ))+
```
You cannot do that, you need to do something like
```
getitemname(@inventory_card1[.@i]) +", 2nd slot"+ getitemname(@inventory_card1[.@i])
```
And so on.
Not a bug, closing

**Closed by dastgir** 2017-06-27 03:00 UTC

**Comment by Likeeit** [comment] 2017-07-01 18:27
@dastgir I have just tested and the names are still not shown, it continues to appear "null".
