### ISSUE TITLE
Problem with Network.conf

### ISSUE THREAD

**Issue by Saekkori** [HerculesWS/Hercules#1807] opened 2017-07-13 23:02 UTC
I have some problem with Network.conf.
I have Stable IP Adress And Opened All port's (6121,5121,6900)
Im trying connect to my server. Good Im in the game.
But My friend's can't connect to my server.

/ Network configuration file

/*
 * List here any LAN subnets this server is in.
 * Example:
 * - char- (or map-) server's IP in LAN is 192.168.0.10
 * - Public IP is 198.51.100.37
 * If the list contains "192.168.0.10:255.255.255.0", any clients connecting
 * from the same 192.168.0.0/24 network will be presented with the LAN IP
 * (192.168.0.10) in the server list, rather than the public IP (198.51.100.37).
 */
lan_subnets: (
    "127.0.0.1:255.255.255.0",
    "192.168.100.4:255.255.255.0",
    "37.232.53.171:255.255.255.0",
)

/*
 * List here any IP ranges a char- or map-server can connect from.
 * A wildcard of "0.0.0.0:0.0.0.0" means that server connections are allowed
 * from ANY IP. (not recommended).
 */
allowed: (
    "127.0.0.1:255.0.0.0",
    
)

/*
 * List here any IP ranges a char- or map-server can connect from. These ranges
 * will also be excluded from the automatic ipban in casee of password failure.
 * Any entry present in this list is also automatically included in the
 * allowed IP list.
 * Note: This may be a security threat. Only edit this list if you know what
 * you are doing.
 */
trusted: (
    "127.0.0.1:255.0.0.0",
    "192.168.100.4:255.255.255.0",
    "37.232.53.171:255.255.255.0",
)

Why? Please Help mee

**Comment by Saekkori** [comment] 2017-07-14 07:09
Char-server console show me this

Char Ip connect 0,0,0,0 => 192.168.100.4
Map Ip connect 0,0,0,0 => 192.168.100.4

**Comment by MishimaHaruna** [comment] 2017-07-14 08:29
- The address `37.232.53.171` doesn't seem to be a LAN IP, and as such you shouldn't list it in the `lan_subnets` block
- In the `trusted` block you're listing `37.232.53.171:255.255.255.0`. This means that you're trusting every IP between `37.232.53.0` and `37.232.53.255`. That's likely not intentional, and seems a security hazard. The most likely value is `37.232.53.171:255.255.255.255` (to trust just that one IP).

You'll also need to correctly configure the `login_ip`, `char_ip`, `map_ip` in the respective config files:

- in login-server.conf, char-server.conf and map-server.conf you may need to set `bind_ip` to the server's LAN IP. This may or may not be necessary, depending on the network and computer configuration (if the server only has one network interface, you can normally skip this)
- in char-server.conf, you need to set `login_ip` to the server's LAN IP. This is always necessary.
- in char-server.conf, you need to set `char_ip` to the server's *public* IP. This is necessary in order to allow connections from outside the LAN.
- in map-server.conf, you need to set `char_ip` to the server's LAN IP. This is always necessary.
- in map-server.conf, you need to set `map_ip` to the server's *public* IP. This is necessary in order to allow connections from outside the LAN.

**Comment by Asheraf** [comment] 2017-07-16 02:31
closing this (assuming that haru's explanation is very clear on how this should be configured + this is not a bug or an issue related to the emulator).

**Closed by Asheraf** 2017-07-16 02:31 UTC
