### ISSUE TITLE
Quest Log System Packet Error to Clients after 2019-06-05f

### ISSUE THREAD

**Issue by victorsantosdevops** [HerculesWS/Hercules#3276] opened 2024-01-25 21:14 UTC
**Describe the bug**

I spent 4 hours yesterday compiling and testing all the clients I found on herc nemo's github, the most recent version in which the name of the monsters in my custom quest appears correctly in the questlog is 2019-06-05f.
Any version after this appears as "Poring" both in Alt + U and on the right side of the screen.

**To Reproduce**
1. Create a quest
2. Alt + U in the xxxx version in Target the correct names of the monsters appear, in the others tested it appears "Poring"
3. On the upper right side in the xxxx version the correct names of the monsters appear, in the others tested it appears "Poring"
4. In the character's head it's the same thing

**Expected behavior**

**Screenshots**
Clients: Packet version: 2021-11-17_Ragexe_1637052357, 2022-03-30_Ragexe_1648440293, 2020-07-15bRagexe, 2020-04-01bRagexe, 2019-12-24aRagexe, 2019-11-20aRagexe, 2019-11-27aRagexe, 2022-04-06_Ragexe_1648707856

[https://cdn.discordapp.com/attachments/306632465294819331/1199959200768466944/image.png?ex=65c47017&is=65b1fb17&hm=7f8b1648862b1e8e9884acbb681e5059b8d6f23c7b552ce0febdbf2256548adf&](url)
[https://cdn.discordapp.com/attachments/306632465294819331/1199957838127185940/image.png?ex=65c46ed2&is=65b1f9d2&hm=5da0ed578edcb10447b8b56a6d50e7eb92687ab655e81f896e4d72d87e3bcc22&](url)

Vídeo 
[https://cdn.discordapp.com/attachments/306632465294819331/1199840189628035162/2024-01-24-19-11-37_Svn6HE1e.mp4?ex=65c40141&is=65b18c41&hm=1df2c4c9fa08004e45f9fd14dc8bc787d519f1c50c1ccb08553c155e8a26ea6b&](url)

Working Fine in  2019-06-05f

[https://cdn.discordapp.com/attachments/306632465294819331/1199959017926168697/image.png?ex=65c46fec&is=65b1faec&hm=8eca2db7724fb64539ed2e5180798ec7bb09c4953219ecdd61b555d41003e623&](url)

**System specs (please complete the following information):**
 - OS: Windows 11
 - Hercules Version [v2023.12]
 - Mode: pre-renewal
 - Packet version: 2021-11-17_Ragexe_1637052357, 2022-03-30_Ragexe_1648440293, 2020-07-15bRagexe, 2020-04-01bRagexe, 2019-12-24aRagexe, 2019-11-20aRagexe, 2019-11-27aRagexe, 2022-04-06_Ragexe_1648707856
 - Client type: main

**Plugins used or source modifications**
mapcache

**Comment by guilherme-gm** [comment] 2024-02-10 04:30
I can't reproduce in 2019-12-24b Ragexe.

quest_db entry:
```
{
	Id: 50533
	Name: "Dragon Hunting"
	Targets: (
	{
		MobId: "ANCIENT_MIMIC"
		Count: 100
	},
	)
},
```

![image](https://github.com/HerculesWS/Hercules/assets/10552039/dfc13e8d-fd68-4e62-b5a3-dbe226b28a54)

Using current master ( 1c386f55b6591d76882f9b510ea52812ceace47f ) it has a few more commits than v2023.12, but nothing that should affect quest log.

Specs:
- Ubuntu 22.04 (using WSL)
- pre-renewal and renewal
- no plugins
- 2019-12-24b Ragexe
- `./configure --enable-packetver=20191224 --disable-renewal CPPFLAGS="-O0"`

**Comment by Asheraf** [comment] 2024-03-01 12:43
Closing this as invalid, the issue was he used a custom mob with Id 5000 which is not in a valid range for monsters.

**Closed by Asheraf** 2024-03-01 12:43 UTC
