### ISSUE TITLE
getd() issue after new release

### ISSUE THREAD

**Issue by bWolfie** [HerculesWS/Hercules#2163] opened 2018-07-30 08:17 UTC
### Issue Prelude

-  [x] I have not modified the source prior to reproducing this issue.
-  [x] I am using the latest version of Hercules.
-  [x] I am aware that this report will be closed or deleted if it becomes obvious that I am stating the false.

### Description

After updating to latest release, `getd()` is causing me issues. It is returning all random bunch of types. I added some warning messages to tell me what type is being received.
```
[Warning]: Type = 8
[Warning]: Type = 8
[Warning]: Type = 8
[Warning]: Type = 64573440
[Warning]: Type = 64573440
[Warning]: Type = 0
[Error]: script:getd: `#ls_showexp` is already used by something that is not a variable.
[Debug]: Source (NPC): OnPCLoginEvent (invisible/not on a map)
```

After using @reloadscript, it works as it should.

### My Script

For reference, I am using a 'Login Settings' script, which will activate certain commands upon login.
First, I set the array in the script.
Second, the commands are used in a function.
```
-	script	Login_Settings	FAKE_NPC,{
OnInit:
	setarray(.Command$,
		// @command, #account_variable
		"@autoloot", "#ls_autoloot",
		"@join #irc", "#ls_channel1",
		"@join #ally", "#ls_channel3",
		"@monsterignore", "#ls_monsterignore",
		"@noask", "#ls_noask",
		"@showexp", "#ls_showexp");
	.Size = getarraysize(.Command$);
	end;
}

function	script	F_LoginSettings	{
	.@Size = getvariableofnpc(.Size, "Login_Settings");
	copyarray(.@Command$[0], getvariableofnpc(.Command$, "Login_Settings"), .@Size);
	for (.@i = 0; .@i < .@Size; .@i += 2) {
		if (!can_use_command(.@Command$[.@i]) && !compare(.@Command$[.@i], "@join"))
			continue;

		if (getd(.@Command$[.@i+1]) != 0) {
			if (.@Command$[.@i] == "@autoloot")
				atcommand(sprintf("%s %d", "@autoloot", #ls_autoloot));
			else if (.@Command$[.@i] == "@killnotify")
				atcommand(sprintf("%s %d", "@killnotify", #ls_killnotify));
			else if (.@Command$[.@i] == "@join #ally") {
				if (getcharid(CHAR_ID_GUILD))
					atcommand(.@Command$[.@i]);
			}
			else
				atcommand(.@Command$[.@i]);
		}
	}
	return;
}
```

**Branch(es):**
- [x] master
- [x] stable

**Hercules rev. hash/commit:** 

Git revision src:

### Operating System

CentOS 7

**Comment by mekolat** [comment] 2018-07-30 13:57
The patch is simple, but I don't know if it could break some things, I'll have to investigate further
```diff
diff --git a/src/map/script.c b/src/map/script.c
--- a/src/map/script.c
+++ b/src/map/script.c
@@ -17800,7 +17800,7 @@ static BUILDIN(getd)

        id = script->search_str(varname);

-       if (id < 0) {
+       if (id < 0 || script->str_data[id].type == C_NOP) {
                id = script->add_str(varname);
                script->str_data[id].type = C_NAME;
        } else if (script->str_data[id].type != C_NAME) {
```
As for type `64573440` I have no idea what causes this, it's not a valid type

**Comment by mekolat** [comment] 2018-07-30 14:39
* if the var is in the sql db:
  * `intif_parse_Registers()` uses the regular `script->set_reg()` so this ensures the type is always `C_NAME` if it is present in the `char_reg_num_db` sql table
* if the var is not in the sql db:
  * if the var was previously used by a script its type will be `C_NAME`
  * if it was never used it will not be in `str_data`, in which case `getunits` would add it and set its type to `C_NAME`

I can't think of anything that would cause the variables to be of type `C_NOP` (and much less `64573440`), and I am completely unable to reproduce this locally

```html
<Dastgir> I suspect memory corruption
```

**Comment by EyesOfAHawk** [comment] 2018-08-19 03:45
My map server randomly crashed. It referenced a sprintf() where I was using getd().

https://pastebin.com/zZTmm6Ks

I have these three lines in my script where it could have refererenced:
```
1.
setd(sprintf(".goodGID_%d", .@i), monster("m_sorter", rand(94, 108), rand(75, 88), getmonsterinfo(.Mob, MOB_NAME), .Mob, 1, sprintf("%s::OnGood", strnpcinfo(NPC_NAME))));

2.
.@GID = getd(sprintf(".goodGID_%d", rand(.Max_Good)));

3.
while (!unitexists(.@GID)) // Note: this my custom command to check unit exists
	.@GID = getd(sprintf(".goodGID_%d", rand(.Max_Good)));
```

**Comment by mekolat** [comment] 2018-08-19 14:03
@EyesOfAHawk this is unrelated to getd, your stack trace clearly shows it's a printf issue. Please open a new GitHub issue for this problem.

**Comment by Helianthella** [comment] 2018-09-13 22:36
@kyeme please update to the latest release

**Comment by dastgirp** [comment] 2019-10-12 18:21
Closing this as the PR was merged containing the fix.
If it still persists, please reopen.

**Closed by dastgirp** 2019-10-12 18:21 UTC
Labels: component:core:scriptengine, status:confirmed, type:bug
