### ISSUE TITLE
Enable/disable NPC do not hide NPCs

### ISSUE THREAD

**Issue by eyes-like-a-hawk** [HerculesWS/Hercules#1560] opened 2017-01-24 13:35 UTC
Unsure if this is intended, but using the script command `enablenpc` or `disablenpc` only ceases their functioning, and does not hide their sprite. You have to also add `hideoffnpc` or `hideonnpc` to get both effects.

This is a problem in instances such as Endless Tower and Nidhoggur's Nest, as there are plenty of warps which need activating, but as it stands now, they appear they are there, when they are in fact not usable.

Just curious if this is intended. I've already gone ahead and added `hideoffnpc`/`hideonnpc` all throughout my files, so it's not too much of an issue to me.

**Comment by Ragn0** [comment] 2017-01-25 04:12
Is this happening only on instances? I think you have a problem with the instance creation and be warped to a map that has not initiated an instance.

In example, this is a part from one of the npcs from Endless Tower script:

```
1@tower,12,393,0	script	1FGate102tower	WARPNPC,2,2,{
	end;

OnInstanceInit:
	disablenpc instance_npcname(strnpcinfo(NPC_NAME));
	end;
```

The npc will be visible in every moment, but, when instance is created executes all the OnInstanceInit label event in all the npcs attached to the instance, making them be invisible until enablenpc is triggered.

Personally, I haven't had problems with enablenpc/disablenpc commands to show/hide npcs.

**Comment by eyes-like-a-hawk** [comment] 2017-01-26 04:21
It's the same for all npcs.

**Comment by guilherme-gm** [comment] 2017-01-29 13:09
It's working fine here too. Do you have source changes? Are you using latest Hercules? What client version are you using?

Tested the following code and first level of Endless Tower:
```
prontera,150,150,4	script	Test	1_M_01,{
	.en = !.en;
	if (.en)
		enablenpc("Test2");
	else
		disablenpc("Test2");
	end;
}

prontera,152,150,4	script	Test2	1_M_01,{
	mes "Hello World";
	close;
}
```

"Test" npc hides "Test2" npc on the second time you click it, then each click will make it appear/disappear.

**Comment by Ridley8819** [comment] 2017-02-12 00:02
The command is working as intended, it sounds you used it wrong or did some edits?

**Comment by Ridley8819** [comment] 2017-03-12 22:03
waited 1 month, closing this

**Closed by Ridley8819** 2017-03-12 22:03 UTC
