### ISSUE TITLE
Snap Dodge not working

### ISSUE THREAD

**Issue by jef924** [HerculesWS/Hercules#1156] opened 2016-02-12 09:21 UTC
I know that there is a setting in the battle conf to turn on/off the snap dodge

but even when turn on, still snap dodge is not working. snapping at the edge of the screen dodging damage is not working. you still receive the damage. same result even on and off

please fix :+1: 

Using the latest hercules

**Comment by kyeme** [comment] 2016-02-12 11:03
Duplicate of https://github.com/HerculesWS/Hercules/issues/638

**Closed** 2016-02-12 23:04 UTC

**Comment by jef924** [comment] 2016-03-31 12:13
BUMP!
