### ISSUE TITLE
New storage code dangerous saving behavior

### ISSUE THREAD

**Issue by rapalooza** [HerculesWS/Hercules#1754] opened 2017-05-30 00:39 UTC
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

[//]: # (Note: Lines beginning with syntax such as this one, are comments and will not be visible in your report!)

### Issue Prelude

[//]: # (Please complete these mandatory steps and check the following boxes by putting an `x` inside the brackets _before_ filing your issue)

-  [x] I am using the latest version of Hercules.
-  [x] I have not modified the source prior to reproducing this issue.
-  [x] I am aware that this report will be closed or deleted if it becomes obvious that I am stating the false.

### Description

Storage doesn't properly save to database, generating a lot of odd behaviors with the possibility of an easy dupping

### Current Behavior

- When transferring a single stakable item, after closing and opening the full stack is now on storage.
- Itens transfered from storage to inventory can be dupped

### Expected Behavior

the storage we all love

### Steps To Reproduce The Issue 1

1.  Do a @storage or storage;
2.  Transfer 1 apple from a stack of 3;
3.  Close the storage window;
4.  Open it again after or without relogging and you will have 2 apples in inventory and 3 in storage.

### Steps To Reproduce The Issue 2

0. Login and quickly
1. Do a @storage or open through an npc storage;
2. Transfer and equipment from invetory to storage
3. Relog
4. Do a @storage or open through an npc storage;
5. Transfer item from storage to inventory
6. Without closing inventory, logout from the game
7. Ending up with 2 for the same item, and same unique_id

**Hercules rev. hash/commit:** 

Git revision src: 
[cb3e2f5](https://github.com/HerculesWS/Hercules/commit/cb3e2f5f3b91d0a1f7711eff9c10ae9a655a74f2)
### Operating System

MSVC 2012

**Comment by tlacson7** [comment] 2017-05-30 01:07
I always do update my core in a weekly basis for my live server.  This time, it did a big problem on my server as when player store items and do char select, that item will not be there in storage. Its lost.  I got tons of player asking retrieval of items and its a big headache.

**Comment by mekolat** [comment] 2017-05-30 01:53
someone should mark this as severity 4 or 5

**Comment by Smokexyz** [comment] 2017-05-30 07:21
Does this still occur after #1751 ?

**Comment by MishimaHaruna** [comment] 2017-05-30 10:35
@Smokexyz part 1 happens because storage_additem() copies the original stack without updating the amount:

```
	if (i == VECTOR_LENGTH(sd->storage.item)) {
		VECTOR_ENSURE(sd->storage.item, 1, 1);
		VECTOR_PUSH(sd->storage.item, *item_data);
		it = &VECTOR_LAST(sd->storage.item);
	} else {
		it = &VECTOR_INDEX(sd->storage.item, i);
		*it = *item_data;
	}
```

The fix:

```
 	if (i == VECTOR_LENGTH(sd->storage.item)) {
 		VECTOR_ENSURE(sd->storage.item, 1, 1);
 		VECTOR_PUSH(sd->storage.item, *item_data);
 		it = &VECTOR_LAST(sd->storage.item);
 	} else {
 		it = &VECTOR_INDEX(sd->storage.item, i);
 		*it = *item_data;
 	}
+	it->amount = amount;
```

(we forgot to port that line over when re-implementing the function)

Currently looking into part 2

**Comment by MishimaHaruna** [comment] 2017-05-30 11:07
Not related to part 2, but I see that we're not setting the `save` flag in some code paths of `storage_additem()`  (in the stackable item case). This also needs to be fixed.

**Comment by MishimaHaruna** [comment] 2017-05-30 11:28
Part 2 is likely to be caused by a missing check in `inter_storage_tosql()`. The final for loop (the one with the `Check for new items.` comment) is disregarding the `updated_p[]` flags.

Suggested fix (untested):

```
 	/**
 	 * Check for new items.
 	 */
 	for (i = 0; i < VECTOR_LENGTH(p->item); i++) {
 		struct item *p_it = &VECTOR_INDEX(p->item, i);
 
-		if (p_it->id != 0)
+		if (updated_p[i] || p_it->id != 0)
 			continue; // Item is not a new entry, so lets continue.
 
 		// Store the remaining items.
```

**Comment by Smokexyz** [comment] 2017-05-30 13:45
@rapalooza This should be fixed in #1756, can you confirm?

**Comment by cshankar00** [comment] 2017-05-30 16:05
Tested new fix and everything fine

**Comment by rapalooza** [comment] 2017-05-30 18:47
@Smokexyz Still being able to duplicate itens by relogin with the storage open;
http://imgur.com/IGZpp1g

**Comment by MishimaHaruna** [comment] 2017-05-31 00:38
I changed the way the storage save function works in #1757, and I can no longer reproduce this after applying it

**Closed** 2017-05-31 00:57 UTC
Labels: severity:5-critical, status:inprogress, type:bug
