### ISSUE TITLE
Server crash pre-renewal, lastest revision

### ISSUE THREAD

**Issue by belfallen** [HerculesWS/Hercules#861] opened 2015-11-13 08:37 UTC
Process information:
Command line: "C:\Users\Administrator\Desktop\Loki Server\map-server.exe" 
Platform: Windows Server 2012 Standard (build 9200)
 CPU: x86_64 CPU, Family 6, Model 26, Stepping 5
Application architecture: x86
Compiler: Microsoft Visual C++ 2012 (v1700)
Git: f7a97b556e05373711998d4f819cf7d89e4b0ce8

Exception:
0xc0000005 EXCEPTION_ACCESS_VIOLATION at location 0x00818DD2 reading from location 0x0B09FB74

Registers:
eax=0b08f630 ebx=7ffde000 ecx=0916552c edx=0b08f630 esi=0018fbe4 edi=0018fce0
eip=00818dd2 esp=0018fbe4 ebp=0018fce0 iopl=0         nv up ei pl nz na po nc
cs=0023  ss=002b  ds=002b  es=002b  fs=0053  gs=002b             efl=00010206

Stacktrace:
#0  0x00818DD2 in party_send_xy_timer+0x112 (tid=(int)18, tick=(long long)1100515076, id=(int)<no data>, data=(int)<no data>) at c:\users\administrator\desktop\loki server\src\map\party.c:885
885				if( !sd || sd->bg_id ) continue;
	sd = (struct map_session_data*)0x0B08F630 <invalid memory>
	i = (int)<no data>
	iter = (struct DBIterator*)0x04F80924 <bytes:50346100DB766100D676610034786100442261006C226100BC546100>
	p = (struct party_data*)0x0916552C <bytes:2D0E000068656F6E677564616D64616E6700000000000000000000000100000006000000048A1E00EA5502004269204B686F6E6720486174000000000000000000000000B00FBB006300CCCCCFCCCCCC0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000030F6080B00000000CC006600000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000010000000000000000000000>
#1  0x0065869D in do_timer+0x54D (tick=(long long)1100515090) at c:\users\administrator\desktop\loki server\src\common\timer.c:398
398					timer_data[tid].func(tid, timer_data[tid].tick, timer_data[tid].id, timer_data[tid].data);
	tid = (int)18
	diff = (long long)-14
#2  0x0062B34C in main+0x24C (argc=(int)1, argv=(char**)0x011EDD88) at c:\users\administrator\desktop\loki server\src\common\core.c:444
444			int next = timer->perform(timer->gettick_nocache());
	next = (int)50
	retval = (int)<no data>
#3  0x009D4BFC in __tmainCRTStartup+0x10C () at f:\dd\vctools\crt_bld\self_x86\crt\src\crt0.c:240
	mainret = (int)<no data>
	managedapp = (int)<no data>
	initret = (int)<no data>
#4  0x009D4DDD in mainCRTStartup+0xD () at f:\dd\vctools\crt_bld\self_x86\crt\src\crt0.c:164
#5  0x755B8543 in BaseThreadInitThunk+0xE (<failed enumerating symbols>)
!!failed enumerating symbols!!#6  0x77ADAC69 in RtlInitializeExceptionChain+0x85 (<failed enumerating symbols>)
!!failed enumerating symbols!!#7  0x77ADAC3C in RtlInitializeExceptionChain+0x58 (<failed enumerating symbols>)
!!failed enumerating symbols!!

**Comment by 4144** [comment] 2015-11-13 16:08
Commit id in message 3 month old. This is not latest code.
About issue dont know is it can be in latest code or not.

**Comment by MishimaHaruna** [comment] 2015-11-17 19:47
Duplicate of #694

**Closed by MishimaHaruna** 2015-11-17 19:47 UTC
