### ISSUE TITLE
Failed Assertion

### ISSUE THREAD

**Issue by Legend95** [HerculesWS/Hercules#1042] opened 2015-12-29 06:31 UTC
Im using Pre-RE setting and never tried to edit src files except for mmo.h and renewal.h
i got that error upon casting "Cast Cancel" (professor job).

Here's an image of the error on mapserver
![nxllx3p](https://cloud.githubusercontent.com/assets/10910799/12034037/47d8feda-ae66-11e5-9390-40f9eef88338.png)

**Comment by dastgir** [comment] 2016-01-05 12:59
enable debug mode? and let us know what it throws
./configure --enable-debug

**Comment by Legend95** [comment] 2016-01-10 07:02
i already enable debug mode and it gives me the same error sir @dastgir 
https://cloud.githubusercontent.com/assets/10910799/12034037/47d8feda-ae66-11e5-9390-40f9eef88338.png

**Comment by 4144** [comment] 2016-01-10 07:43
after enabled debug, need run: make clean
and after: make
if even this not help, probably need run configure like this: ./configure --enable-debug=gdb

**Comment by Legend95** [comment] 2016-01-10 14:25
(gdb) [Error]: --- failed assertion --------------------------------------------
[Error]: skill.c:175: 'skill_lv > 0' in function `skill_get_sp'
[Error]: ./map-server() [0x824e0e8]
[Error]: ./map-server() [0x81b681e]
[Error]: ./map-server() [0x81f73b4]
[Error]: ./map-server() [0x81d7618]
[Error]: ./map-server() [0x823bf90]
[Error]: ./map-server() [0x823a7ee]
[Error]: ./map-server() [0x80b3b47]
[Error]: ./map-server() [0x80c170e]
[Error]: ./map-server() [0x825a2d4]
[Error]: ./map-server() [0x825600a]
[Error]: --- end failed assertion ----------------------------------------

**Comment by Asheraf** [comment] 2018-05-14 22:01
Unable to reproduce on 5c9056c183421df41b546dc3031d251ee6c963b5, also too old and no useful information's, closing for now.

**Closed by Asheraf** 2018-05-14 22:01 UTC
Labels: component:core, status:needs-info, type:bug
