### ISSUE TITLE
map_zone_db and GvG mapflag

### ISSUE THREAD

**Issue by AnisotropicDefixation** [HerculesWS/Hercules#572] opened 2015-06-26 20:07 UTC
Refer to this:
http://herc.ws/board/topic/302-introducing-hercules-map-zone-database/page-5#entry57634

It goes like this:

Boot the server, everything's working, PvP-specific skills and gear aren't working in castles since WoE isn't active.

WoE begins, GvG mapflag is applied and now all that stuff can be used.

WoE ends, GvG mapflag is turned off, now this is where it breaks, the next time WoE starts, mapflag won't properly apply and all WoE-specific stuff will be disabled since maps are treated as normal zones. Setting it manually with @mapflag doesn't work either. Only solution is to reload scripts or reboot and having to do this after every WoE isn't exactly desirable.

This is a rather serious issue that's been around for quite a long time.

**Comment by MishimaHaruna** [comment] 2015-06-28 14:30
Never heard of this before o.o Does it only affect disabled items/skills or also other map settings from the map_zone_db (such as damage reduction or knockback)?

**Comment by AnisotropicDefixation** [comment] 2015-06-28 21:08
Only items and skills, not that long ago it also cancelled GvG reductions for spell damage, though that was fixed already.

**Comment by AnisotropicDefixation** [comment] 2015-07-06 12:22
Would be nice to have some feedback on this from others.

**Comment by MishimaHaruna** [comment] 2015-08-29 14:31
I'm not really able to reproduce this, can you provide a minimal map_zone_db where this happens, so that we have a similar situation?

**Comment by AnisotropicDefixation** [comment] 2015-08-29 22:06
Basically any map with gvgon enabled by default, you an replicate this with either script call or atcommand by turning gvg off and then on again, now you won't be able to use gvg specific skills and items (Arrullo, Deep Sleep Lullaby, Manhole, Siege potions, etc) even though it's enabled back again.

**Comment by kyeme** [comment] 2015-08-30 02:50
@MishimaHaruna I have a suggestion regardingthis :D
http://herc.ws/board/topic/10452-map-with-multiple-zone/

**Comment by MishimaHaruna** [comment] 2015-08-30 15:33
@AnisotropicDefixation I was able to reproduce it now. It only happens with maps that already have the GvG flag at server startup (so, for example, `guild_vs2`, but not the WoE castles).

In WoE castles it's even worse - they just don't work, from what I see.

Maps that have the GvG flag at server startup, are assigned to the `GvG` zone, which works as intended. Once you `@gvgoff`, they get assigned to the `Normal` zone, and after the next `@gvgon`, they are changed to `Normal+GvG`. WoE castles start with the `Normal` zone, and once you `@agitstart` they're changed to `Normal+GvG`.

When merging zones, like in `Normal+GvG`, skills that were disabled in `Normal`, but aren't disabled in `GvG`, are still disabled (because there's no entry in the `GvG` zone to override the disabled entry in `Normal`), and as such, skills like `WM_LULLABY_DEEPSLEEP` are never enabled in WoE, apparently (is it possible that nobody noticed?)

Server startup (map with GvG by default):
```
[Debug]: Map guild_vs2 was set to zone GvG with 17 disabled skills:
AL_TELEPORT [ player ]
AL_WARP [ player ]
WZ_ICEWALL [ player ]
TF_BACKSLIDING [ player ]
RG_INTIMIDATE [ player ]
WE_CALLPARTNER [ player ]
HP_ASSUMPTIO [ player ]
HP_BASILICA [ player ]
CG_MOONLIT [ player ]
WE_CALLPARENT [ player ]
WE_CALLBABY [ player ]
CR_CULTIVATION [ player ]
NJ_KIRIKAGE [ player ]
CASH_ASSUMPTIO [ player ]
BS_GREED [ player ]
SC_FATALMENACE [ player ]
SC_DIMENSIONDOOR [ player ]
```

`@gvgoff`:
```
[Debug]: Map guild_vs2 was set to zone Normal with 5 disabled skills:
- WM_LULLABY_DEEPSLEEP [ player ]
- WM_SIRCLEOFNATURE [ player ]
- WM_SATURDAY_NIGHT_FEVER [ player ]
- SO_ARRULLO [ player ]
- CG_HERMODE [ player ]
```

`@gvgon` again:
```
[Debug]: Map guild_vs2 was set to zone GvG+Normal with 22 disabled skills:
- AL_TELEPORT [ player ]
- AL_WARP [ player ]
- WZ_ICEWALL [ player ]
- TF_BACKSLIDING [ player ]
- RG_INTIMIDATE [ player ]
- WE_CALLPARTNER [ player ]
- HP_ASSUMPTIO [ player ]
- HP_BASILICA [ player ]
- CG_MOONLIT [ player ]
- WE_CALLPARENT [ player ]
- WE_CALLBABY [ player ]
- CR_CULTIVATION [ player ]
- NJ_KIRIKAGE [ player ]
- CASH_ASSUMPTIO [ player ]
- BS_GREED [ player ]
- SC_FATALMENACE [ player ]
- SC_DIMENSIONDOOR [ player ]
- WM_LULLABY_DEEPSLEEP [ player ]
- WM_SIRCLEOFNATURE [ player ]
- WM_SATURDAY_NIGHT_FEVER [ player ]
- SO_ARRULLO [ player ]
- CG_HERMODE [ player ]
```

`@agitstart`:
```
[Debug]: Map prtg_cas05 was set to zone GvG+Normal with 22 disabled skills:
- AL_TELEPORT [ player ]
- AL_WARP [ player ]
- WZ_ICEWALL [ player ]
- TF_BACKSLIDING [ player ]
- RG_INTIMIDATE [ player ]
- WE_CALLPARTNER [ player ]
- HP_ASSUMPTIO [ player ]
- HP_BASILICA [ player ]
- CG_MOONLIT [ player ]
- WE_CALLPARENT [ player ]
- WE_CALLBABY [ player ]
- CR_CULTIVATION [ player ]
- NJ_KIRIKAGE [ player ]
- CASH_ASSUMPTIO [ player ]
- BS_GREED [ player ]
- SC_FATALMENACE [ player ]
- SC_DIMENSIONDOOR [ player ]
- WM_LULLABY_DEEPSLEEP [ player ]
- WM_SIRCLEOFNATURE [ player ]
- WM_SATURDAY_NIGHT_FEVER [ player ]
- SO_ARRULLO [ player ]
- CG_HERMODE [ player ]
```

`@agitend`
```
[Debug]: Map prtg_cas05 was set to zone Normal with 5 disabled skills:
- WM_LULLABY_DEEPSLEEP [ player ]
- WM_SIRCLEOFNATURE [ player ]
- WM_SATURDAY_NIGHT_FEVER [ player ]
- SO_ARRULLO [ player ]
- CG_HERMODE [ player ]
```

@kyeme Replied

**Comment by MishimaHaruna** [comment] 2015-08-30 15:38
Forgot to mention, those debug logs were produced by:

```
diff --git a/src/map/map.c b/src/map/map.c
index 6e35e6b..6a4af58 100644
--- a/src/map/map.c
+++ b/src/map/map.c
@@ -4730,6 +4730,26 @@ void map_zone_apply(int m, struct map_zone_data *zone, const char* start, const

                npc->parse_mapflag(map->list[m].name, empty, flag, params, start, buffer, filepath, NULL);
        }
+       ShowDebug("Map %s was set to zone %s with %d disabled skills", map->list[m].name, map->list[m].zone->name, map->list[m].zone->disabled_skills_count);
+       if (map->list[m].zone->disabled_skills_count)
+               ShowMessage(":");
+       for (i = 0; i < map->list[m].zone->disabled_skills_count; ++i) {
+               ShowMessage("\n- %s [", skill->get_name(map->list[m].zone->disabled_skills[i]->nameid));
+               if (map->list[m].zone->disabled_skills[i]->type == BL_ALL) {
+                       ShowMessage(" all");
+               } else if (map->list[m].zone->disabled_skills[i]->type == BL_NUL) {
+                       ShowMessage(" none");
+               } else {
+                       if (map->list[m].zone->disabled_skills[i]->type&BL_PC) ShowMessage(" player");
+                       if (map->list[m].zone->disabled_skills[i]->type&BL_HOM) ShowMessage(" homun");
+                       if (map->list[m].zone->disabled_skills[i]->type&BL_MER) ShowMessage(" mercenary");
+                       if (map->list[m].zone->disabled_skills[i]->type&BL_MOB) ShowMessage(" monster");
+                       if (map->list[m].zone->disabled_skills[i]->type&BL_ELEM) ShowMessage(" elemental");
+                       if (map->list[m].zone->disabled_skills[i]->type&BL_PET) ShowMessage(" pet");
+               }
+               ShowMessage(" ]");
+       }
+       ShowMessage("\n");
 }
 /* used on npc load and reload to apply all "Normal" and "PK Mode" zones */
 void map_zone_init(void) {
```

**Comment by AnisotropicDefixation** [comment] 2015-08-30 15:53
Oh yeah, what I did myself as a workaround was setting WoE castles as gvg by default and removing gvgon/gvgoff from the woe handling script.

**Closed** 2015-09-28 23:28 UTC
Labels: component:core, status:ready, type:bug
