### ISSUE TITLE
Client side stuck at trading

### ISSUE THREAD

**Issue by pengc2010** [HerculesWS/Hercules#740] opened 2015-09-24 17:40 UTC
To reproduce it:
Try to trade with other players while talking with any npc.
The message box will disappear and you get stuck.

**Comment by kyeme** [comment] 2015-09-26 08:11
I can't reproduce

**Comment by Jedzkie** [comment] 2018-04-04 18:53
This is also present in official servers.

**Comment by Jedzkie** [comment] 2018-04-04 19:04
This issue is already fixed by this commit: https://github.com/HerculesWS/Hercules/pull/1694 closing this now.

**Closed by Jedzkie** 2018-04-04 19:04 UTC
Labels: component:client-interface, component:core, status:confirmed, status:inprogress, type:bug
