### ISSUE TITLE
Map server crashed when trigger the OnSellItem event label

### ISSUE THREAD

**Issue by Emistry** [HerculesWS/Hercules#1791] opened 2017-06-24 20:35 UTC
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

[//]: # (Note: Lines beginning with syntax such as this one, are comments and will not be visible in your report!)

### Issue Prelude

[//]: # (Please complete these mandatory steps and check the following boxes by putting an `x` inside the brackets _before_ filing your issue)

-  [x] I have not modified the source prior to reproducing this issue.
-  [x] I am using the latest version of Hercules.
-  [x] I am aware that this report will be closed or deleted if it becomes obvious that I am stating the false.

### Description
Map server crashed when trigger the **OnSellItem** event label

[//]: # (Description of the problem or issue at length.)
[//]: # (Please specify any battle configuration related to the components of this issue that have been changed from the default values. This will allow quicker determination of the cause of the problem.)

### Current Behavior
Map server crashed when trigger the **OnSellItem** event label
Happen when storing values into the array `@slot_opt_idx....`

[//]: # (Describe at length what you noticed during your analysis.)
[//]: # (If this is a crash, post the core/stack-dump or crash-log to https://gist.github.com/)
[//]: # (If you are referencing from sources such as iROwiki or ratemyserver.net, please quote specific information rather than providing the links alone.)

### Expected Behavior
Wont crash the map-server, and able to trigger the **OnSellItem** event label, and store all the value into respective arrays.

[//]: # (Tell us what should happen instead.)

### Steps To Reproduce The Issue

1. Load the NPC script provided here. 
```
prontera,155,181,5	script	Sample#npc	4_F_KAFRA1,{
	npcshopattach "sample_shop",1;
	callshop "sample_shop", 2;
	end;
		
	OnSellItem:
		mes "Success. no problem.";
		close;
}

-	shop	sample_shop	-1,909:-1
```

2. Talk to the NPC
3. Pick some items and sell it to NPC.
4. Map-server crashed.
![Error](http://i.imgur.com/agUDhra.png)

**Branch(es):**
- [x] master
- [ ] other

**Hercules rev. hash/commit:** 

Git revision src: https://github.com/HerculesWS/Hercules/commit/ae82ea6b23d3bd068eb54fb7199fe0b35cf4ef64

[//]: # (Copy the first 3 lines of the login-server, char-server or map-server startup.)
[//]: # ( [Info]: Hercules 64-bit for Mac OS X )
[//]: # ( [Info]: Git revision src: 'a5918b329ca0826b04dca32ede783586403f58db' )
[//]: # ( [Info]: Git revision scripts: 'a5918b329ca0826b04dca32ede783586403f58db' )

### Operating System
Window 10.

[//]: # (Mac OS X 10.12.3 16D32 [x86_64])
[//]: # (Thank you for adhering to this process! It ensures your issue is resolved quickly and that neither your nor our time is needlessly wasted.)
[//]: # (This template is for problem reports. For other types of report, edit it accordingly.)
[//]: # (For fixes please create a Pull Request.)

**Comment by mekolat** [comment] 2017-06-25 02:27
```gdb
[Thread 0x7fffff780700 (LWP 492) exited]
[Inferior 1 (process 492) exited with code 01]
(gdb) bt full
No stack.
```
Great, a clean exit

**Comment by mekolat** [comment] 2017-06-25 03:56
```diff
                for (j = 0; j < MAX_ITEM_OPTIONS; j++) {
+                       if (!item->option[j].index) {
+                               continue;
+                       }
+
                        intptr_t opt_idx = item->option[j].index;
                        intptr_t opt_value = item->option[j].value;
```

If this bug is here it might be in other places too, so I'm gonna review that whole item option PR once again

**Comment by dastgir** [comment] 2017-06-25 10:26
https://github.com/HerculesWS/Hercules/pull/1782
^ I already have PR opened?

**Comment by dastgir** [comment] 2017-06-25 10:27
Duplicate of https://github.com/HerculesWS/Hercules/issues/1772

**Closed by dastgir** 2017-06-25 10:27 UTC
