### ISSUE TITLE
make sql using CentOS 5 64-bit

### ISSUE THREAD

**Issue by reunite-ro** [HerculesWS/Hercules#1167] opened 2016-02-23 14:40 UTC
when i make sql using CentOS 6 x86_64, theres error about socket you can see below : 

```
make[1]: Entering directory `/root/hercules/Hercules.git/trunk/src/common'
        CC      socket.c
In file included from /usr/include/asm-x86_64/byteorder.h:30,
                 from /usr/include/asm/byteorder.h:5,
                 from /usr/include/linux/tcp.h:21,
                 from socket.c:49:
/usr/include/linux/byteorder/little_endian.h:43: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘__cpu_to_le64p’
/usr/include/linux/byteorder/little_endian.h:47: error: expected ‘;’, ‘,’ or ‘)’ before ‘*’ token
/usr/include/linux/byteorder/little_endian.h:67: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘__cpu_to_be64p’
/usr/include/linux/byteorder/little_endian.h:71: error: expected ‘;’, ‘,’ or ‘)’ before ‘*’ token
make[1]: *** [obj_all/socket.o] Error 1
make[1]: Leaving directory `/root/hercules/Hercules.git/trunk/src/common'
make: *** [common_sql] Error 2
```

Cant compile, i solve it by commenting a few lines in socket.c : 
```
//#if defined __linux__ || defined __linux
//#       include <linux/tcp.h>
//#else
```

it worked for me.

**Comment by dastgir** [comment] 2016-02-27 11:33
Never had it before on my CentOS
@4144 @MishimaHaruna

**Comment by 4144** [comment] 2016-02-27 12:51
this is look like some issue with headers. Probably wrong headers in this system.
It can be fixed if change headers order or may not.

By disabling this includes it may affect latency a bit, but server will works without this includes.

**Comment by reunite-ro** [comment] 2016-02-27 13:05
is there any fix then for this distro if that includes disabled going to affect latency?

**Comment by MishimaHaruna** [comment] 2016-02-27 15:08
I'm unable to reproduce this on CentOS 6 (fully up to date). What compiler and configure flags are you using?

**Comment by reunite-ro** [comment] 2016-02-27 15:25
are u using CentOS 6 x86_64 ?

**Comment by MishimaHaruna** [comment] 2016-02-27 15:36
Yes, I tested on a fully up to date CentOS 6 x86_64 (version 6.7), running kernel 2.6.32-573.18.1.el6.x86_64 and using gcc version 4.4.7. I compiled with the default configure flags, and it didn't show any errors or warnings.

**Comment by reunite-ro** [comment] 2016-03-04 09:30
Im sorry my mistake, seeing other VPS

its CentOS 5 64-bit

**Comment by MishimaHaruna** [comment] 2016-03-06 23:15
I'm sorry, but I don't have access to a CentOS 5 machine, nor we do focus on such an old OS (for reference, CentOS 6 was released in 2011, CentOS 7 in 2014).
We can accept pull requests to fix issues like this, but we can't/won't test on such old systems.

**Closed by MishimaHaruna** 2016-03-06 23:15 UTC
Labels: component:other, status:unreproducible, type:bug
