### ISSUE TITLE
Cart Termination can be reflected.

### ISSUE THREAD

**Issue by xHelenax** [HerculesWS/Hercules#1212] opened 2016-03-21 11:36 UTC
I found an issue that Cart Termination can be reflected with equipment and cards such as Orc Lord. 

Cart Termination however, is -**not**- a physical melee skill (as +% damage multipliers (such as Turtle General/Hydra Card) do not boost the damage). 

Therefore, Cart Termination should not be reflectable.

**Comment by Jedzkie** [comment] 2016-03-21 12:33
Aegis Behavior:

![screenmichiro002](https://cloud.githubusercontent.com/assets/4826387/13918747/1cbb2424-efa4-11e5-9cc8-1c5ceb98aae0.jpg)

![screenmichiro003](https://cloud.githubusercontent.com/assets/4826387/13918753/275caae2-efa4-11e5-8d09-4a908e0a0b1c.jpg)

**Comment by xHelenax** [comment] 2016-03-21 12:44
It shouldn't be like that. CT isn't a melee skill, it hits with cart/zeny.  CT bypasses other reflect features such as the Reflect Shield skill (source: http://irowiki.org/wiki/High_Speed_Cart_Ram). 
Why would it not work like that with reflect cards?

**Comment by Jedzkie** [comment] 2016-03-21 13:09
Yeah we know reflect is reflect but the picture says it, it does still reflect with orc lord card.

**Comment by xHelenax** [comment] 2016-03-23 09:47
Can this please be reopened? I was told by Mysterious that Hercules is following kRO behaviour and not Aegis. I do not have a Whitesmith on kRO to my disposal so I can not test, but until then I'm pretty sure that this is _not_ kRO behaviour. Thanks. :)

**Comment by hemagx** [comment] 2016-03-23 09:52
kRO = Aegis, aegis is the project used by kRO to run ro servers
However this issue opened for further investigations

**Comment by WillTheDoggy** [comment] 2016-03-23 14:07
In pre-renewal, Cart-Termination does not reflect.

In renewal, it does.

**Comment by kyeme** [comment] 2016-03-23 14:27
@WillTheDoggy any source?

**Comment by Playtester** [comment] 2016-03-23 16:18
I have no way to test pre-renewal and jedzkie already tested it on renewal. So I'd say working as intended unless there's some proof for pre-re.

**Comment by WillTheDoggy** [comment] 2016-03-23 16:37
I have a iRO Classic account that I will test at home. I will follow-up.

**Comment by malufett** [comment] 2016-03-23 17:39
as I remember @kyeme confirm this before in Pre before we implemented the official reflect behavior in which I reconfirmed it in RE using Aegis and kRO...

**Comment by xHelenax** [comment] 2016-03-25 11:42
So it is working as intended after all?

**Comment by Jedzkie** [comment] 2016-04-01 04:36
@hemagx When you have time to test this?

**Comment by hemagx** [comment] 2016-04-01 22:18
they ask for pre-re i can't help.

**Comment by Lavenblade** [comment] 2016-04-02 20:02
I think most people remember Cart Term NOT being reflected in Pre-RE. In fact, most people I've asked believe that it should not be reflected. Leaving this as is simply because it's reflected in RE doesn't sound right. If nobody can confirm, there should be some sort of toggle in the configuration.

**Comment by malufett** [comment] 2016-04-02 20:18
@Lavenblade 
I think most of them are private server players and not aware on the difference between the types of reflect...anyway if there a chance someone got solid proof or source the better..

**Comment by hemagx** [comment] 2016-04-02 20:54
ok, so it's about pre-re or re ? generally i have Aegis issue right
now,. but if it's pre-re i can't really test it.

2016-04-02 22:18 جرينتش+02:00, malufett <notifications@github.com>:

**Comment by Jedzkie** [comment] 2016-04-03 02:48
Classic iRO is our last option.

**Comment by Lavenblade** [comment] 2016-04-03 02:50
I'll see if I have any friends who have accounts on iRO. If anyone else does or knows anybody, please let us know. Make sure you're checking for PreRE.

**Comment by kyeme** [comment] 2016-04-03 07:14
Shield Reflect vs. High Speed Cart Ram
"HSCR pierces shield reflect"
pre-renewal source: http://z14.invisionfree.com/proiriscommunity/index.php?showtopic=5316

~~

Orc Lord / V. Mant. or item with reflect vs. High Speed Cart Ram
pre-renewal source: http://forums.irowiki.org/showthread.php?t=5485
"Tested: Valk Manteau DOES reflect High Speed Cart Ram."

**Comment by xHelenax** [comment] 2016-04-03 10:18
Wow, okay... that's new, so none of the servers i've/we've played previously was following the official behavior. Unfortunately I liked that non-official behavior. Can anyone point me in the right direction how to make it so that it can't be reflected? ):

**Comment by Lavenblade** [comment] 2016-04-03 16:04
I think it makes more sense to not reflect it... % Damage cards do not even work, so it shouldn't reflect. Not only that, but think balance. They have no range, poor mobility. Single target dps. Low HP pools. The ranged attack they do have doesn't do much.

**Comment by Ridley8819** [comment] 2016-10-10 20:49
Since there were no reply since half a year I'm closing this. If you still want to request this customization please use the forums.

**Closed by Ridley8819** 2016-10-10 20:49 UTC
Labels: status:need-aegis-confirmation
