### ISSUE TITLE
Error Skill.c:180

### ISSUE THREAD

**Issue by ragnasound** [HerculesWS/Hercules#1750] opened 2017-05-28 01:53 UTC
(05/27/2017 19:20:12) [ Error ] : skill.c:180: 'skill_lv > 0' in function `skill_get_sp'
(05/27/2017 19:20:12) [ Error ] : ./map-server(assert_report+0x80) [0x64fd90]
(05/27/2017 19:20:12) [ Error ] : ./map-server(skill_get_sp+0xcb) [0x5b96db]
(05/27/2017 19:20:12) [ Error ] : ./map-server(skill_castend_nodamage_id+0xe93) [0x5f4ea3]
(05/27/2017 19:20:12) [ Error ] : plugins/HPMHooking_map.so(HP_skill_castend_nodamage_id+0xeb) [0x7f65546a921b]
(05/27/2017 19:20:12) [ Error ] : ./map-server(skill_castend_id+0x12b5) [0x5ca2f5]
(05/27/2017 19:20:12) [ Error ] : ./map-server(unit_skilluse_id2+0xeac) [0x63e5ec]
(05/27/2017 19:20:12) [ Error ] : plugins/HPMHooking_map.so(HP_clif_pUseSkillToId+0x8e) [0x7f655463b4ae]
(05/27/2017 19:20:12) [ Error ] : ./map-server(clif_parse+0x1bd) [0x4b034d]
(05/27/2017 19:20:12) [ Error ] : ./map-server(do_sockets+0x25e) [0x65e4ce]
(05/27/2017 19:20:12) [ Error ] : ./map-server(main+0x1a2) [0x658b92]

**Comment by mekolat** [comment] 2017-05-28 03:17
seems to be a duplicate of https://github.com/HerculesWS/Hercules/issues/1748

**Closed** 2017-05-28 15:41 UTC
