### ISSUE TITLE
Outdated rAthena Upgrade query

### ISSUE THREAD

**Issue by lelouch22** [HerculesWS/Hercules#1568] opened 2017-02-07 05:44 UTC
The last revision was about 3 years ago so it kinda outdated

Also i already made a topic about this on board
http://herc.ws/board/topic/14262-r-updated-rathena-upgrade-sql/

**Comment by Asheraf** [comment] 2017-02-07 11:48
duplicate of #900

**Closed** 2017-03-12 22:56 UTC
