### ISSUE TITLE
unexpected character when using ++var; inside conditions without { }

### ISSUE THREAD

**Issue by Ragn0** [HerculesWS/Hercules#1553] opened 2017-01-22 00:13 UTC
This is a minor issue, when use `++var;` assignment inside conditional without { } produces console error. Example:

```
	if (true) 
		++@test;
```
The last will produce script error. However, this other don't:

```
	if (true) {
		++@test;
	}
```
This is a minnor issue since it can be used `@test += 1;` instead or put the { }, but still an issue.

**Comment by Asheraf** [comment] 2017-01-22 02:16
Duplicate of #705

**Closed** 2017-01-22 02:26 UTC
