### ISSUE TITLE
Storage item dupe issue

### ISSUE THREAD

**Issue by cshankar00** [HerculesWS/Hercules#1758] opened 2017-06-01 19:00 UTC
[//]: # (**********************************)
[//]: # (** Fill in the following fields **)
[//]: # (**********************************)

[//]: # (Note: Lines beginning with syntax such as this one, are comments and will not be visible in your report!)

### Issue Prelude

[//]: # (Please complete these mandatory steps and check the following boxes by putting an `x` inside the brackets _before_ filing your issue)

-  [x] I have not modified the source prior to reproducing this issue.
-  [x] I am using the latest version of Hercules.
-  [x] I am aware that this report will be closed or deleted if it becomes obvious that I am stating the false.

### Description

[//]: # (Description of the problem or issue at length.)
[//]: # (Please specify any battle configuration related to the components of this issue that have been changed from the default values. This will allow quicker determination of the cause of the problem.)

1.
Item dupe for stack able items still exist, whenever u get certain amount of item from storage like 50 poring coin out of 100 and then keep storage open (even while storage closed) and do character select and then login back as fast as possible causing item dupe (like 50 coin in inventory and 100 coin in storage)

To generate this bug require at list get 2 or more kind of items from storage to inventory like apple and speed potion. 

This bug apply for all stack able items, usable to misc items can be duped using this.  

2.
Whenever stacked item stored in storage like 100 poring coin and 5 poring card and then keep open storage (even after closing storage) and then doing character select and login back as fast as possible cause item missing in inventory and storage.

[//]: # (Tell us what should happen instead.)

**Branch(es):**
- [x] master
- [ ] other

**Hercules rev. hash/commit:** 

Latest Hercules Version

**Comment by cshankar00** [comment] 2017-06-01 19:02
Can someone expert test this on offline server? because there should be many cases like this.

**Comment by mekolat** [comment] 2017-06-01 19:35
@cshankar00 can you please confirm which commit you are on? do `git rev-parse HEAD` and paste the output

**Comment by 4144** [comment] 2017-06-01 19:55
@cshankar00 please say your hercules revision.

**Comment by cshankar00** [comment] 2017-06-01 22:27
upto date

**Comment by cshankar00** [comment] 2017-06-01 22:28
Revision 18758

**Comment by rapalooza** [comment] 2017-06-01 22:49
Hmmm, i'm couldn't reproduce this one. make sure to build the solution after checking it.

**Comment by cshankar00** [comment] 2017-06-01 22:51
get 2 or more type of item from storage

**Comment by cshankar00** [comment] 2017-06-01 22:51
Yes i have build solution

**Comment by maqc1** [comment] 2017-06-02 01:42
I have the same issue (items go missing in storage after login off/login on). Issue appeared after I updated Hercules, May 30th, commit b950a58. Hope this helps!

**Comment by mekolat** [comment] 2017-06-02 01:56
@maqc1 @cshankar00  there was another patch after b950a58 please update to 47a1e67 or more recent

**Comment by cshankar00** [comment] 2017-06-02 08:58
Well i'm using SVN update to update my hercules and it's up to date with latest commit and yes i have rebuild solution.

**Comment by maqc1** [comment] 2017-06-02 11:51
Same here, I just updated to f30edc7 and the issue is still there.

**Comment by MishimaHaruna** [comment] 2017-06-02 12:45
I'm unable to reproduce the issue with the steps described. How do you reproduce it?

**Comment by MishimaHaruna** [comment] 2017-06-02 12:58
Actually, considering your 'as fast as possible', this sounds like a race condition that we probably always had (but it originally only affected homunculu, mercenaries, elementals, questlog).

Can you test if commit ab840df fixes your issue? I'm unable to reproduce it at all locally (my character server is likely faster than my client)

**Comment by cshankar00** [comment] 2017-06-02 13:36
@MishimaHaruna well when i get single type of item from storage like poring coin, it does not dupe items, but when i get more than 2 types of items like Poring coin and war badge (50 poring coin out of 100 and 50 war badge out of 100) and then re-log, i got 50 poring coin and war badge in inventory and 100 poring coin and war badge in storage.

Does right click on folder and do SVN update get all update? or just last update? does it skip update?
my herc directory shows up to date.

**Comment by Smokexyz** [comment] 2017-06-02 14:18
Should be fixed after #1759 is merged.

**Comment by cshankar00** [comment] 2017-06-02 21:09
Thanks, i'm no long able to produce this bug.

**Closed** 2017-06-02 22:10 UTC
