### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by julinhobrow** [HerculesWS/Hercules#1634] opened 2017-03-14 15:06 UTC
but this error is on a clean herc, when you say but pointing on the fact that it's not possible to have this error in a clean herc. you say im lying. because is a clean herc install
what i do only
git clone https://github.com/HerculesWS/Hercules.git
cd Hercules
./configure
make clean
make sql

and give me
script.c: In function ‘buildin_classchange’:
script.c:13939:4: error: too many arguments to function ‘clif->class_change’
clif->class_change(bl, class, type, sd);
^
script.c:13942:3: error: too many arguments to function ‘clif->class_change’
clif->class_change(bl, class, type, NULL);

i put now a rathena, becauce peoples here dont give a solution.

**Comment by 4144** [comment] 2017-03-14 15:17
You again not follow issue header...
And this error impossible in this lines.

Can you show ALL your commands from terminal and output?
Probably git clone failed because Hercules directory already exists?

**Comment by iRagno** [comment] 2017-03-14 20:23
Devs doesn't deny to give a solution, @julinhobrow, they are only requiring to fill a template with information required to solve this issue and you are not following that. Specifically they need git hash to check for error in that revision and you don't give it, that is the reason they close your issue #1622.

In actual version of emulator (that is, 7b4d4fb92603ef1e622b52e777cd5ac1b7f97d55) that error doesn't happen, and if can't reproduce if not possible to solve it. It would happen in Hercules, or rAthena, or eAthena, or every emulator you can use.

Maybe you could open a new topic in boards requesting support for the problem you have, because it seems it's entirely local (at least for the reason they give you in last issue).

Here you have some examples of issues being fulfilled with new required template: #1625, #1626, #1629.

**Comment by Smokexyz** [comment] 2017-03-21 17:34
Closing this issue due to insufficient and inaccurate information.

**Closed by Smokexyz** 2017-03-21 17:34 UTC
