### ISSUE TITLE
show_monster_hp_bar

### ISSUE THREAD

**Issue by kyeme** [HerculesWS/Hercules#744] opened 2015-09-26 01:42 UTC
// Show hp bar on monsters? (Default: yes)
// NOTE: only works on client 2012-04-04aRagexeRE onwards
show_monster_hp_bar: yes

when set to NO , I can still view mob hp bar
Im using 2015-05-13
![hpbar](https://cloud.githubusercontent.com/assets/4656578/10115194/c4d457c8-6432-11e5-8e04-c4b15d2efe2a.jpg)

**Comment by MishimaHaruna** [comment] 2015-09-28 18:07
On `PACKETVER >= 20120712`, the mob HP information appears to be bundled with the idle/spawn/walking packets (see `clif_set_unit_idle`, `clif_spawn_unit`, `clif_set_unit_walking`).
The fix should involve sending `-1` as `HP` and `MaxHP`, so that the bar is not displayed (which is what we already do if the unit is not a mob).

Since: 18f222b
Related: 19b8cbb8

**Comment by Jedzkie** [comment] 2015-10-27 06:04
Bump @MishimaHaruna

**Comment by hemagx** [comment] 2015-12-16 17:47
i tried it but i can't face the bug at all, more information would be helpful ?
client date, server settings ?

**Comment by MishimaHaruna** [comment] 2015-12-17 02:22
Any client > 2015 should allow you to reproduce this (see `clif_set_unit_idle`, `clif_spawn_unit`, `clif_set_unit_walking`)

**Comment by dastgir** [comment] 2015-12-20 16:45
#978 
Actually need to send entity packets in new client, for HP bars

**Comment by Jedzkie** [comment] 2015-12-22 13:33
@hemagx @MishimaHaruna I re-opened this issue because, it shows the HP of the MVP which is not the behavior of Official Servers.

**Comment by hemagx** [comment] 2015-12-22 16:34
@Jedzkie actually this clients have a value for boss status, and if it's boss give give bigger HP Bar.
so for now we will close this, until it's confirmed boss HP should not be showed, as it make no sense.

**Comment by MishimaHaruna** [comment] 2016-01-13 11:01
Reopening this for the time being. It seems very suspicious, if we show every mob's HP (including emperium and MVPs)

Due to recent changes in eb0d0dc6, the impact of this this escalated to affect all recent clients starting from 2012 (2012~2013 clients receive the HP bar from both the `clif->set_unit_XXX()` (regardless of the mob being a boss) and `clif->monster_hp_bar()` (which is only sent when the mob is not a boss). - that's a separate issue to fix, but related to this.

**Comment by Jedzkie** [comment] 2016-01-14 06:42
@MishimaHaruna please check this http://youtu.be/JFoco9jKdoU

**Comment by Jedzkie** [comment] 2018-04-02 11:02
Closing this issue, already fixed.

**Closed by Jedzkie** 2018-04-02 11:02 UTC
Labels: component:client-interface, component:core, status:needs-aegis-confirmation, type:bug
