### ISSUE TITLE
Party dismissed when leader leave

### ISSUE THREAD

**Issue by zackdreaver** [HerculesWS/Hercules#1107] opened 2016-01-16 16:16 UTC
Test Mode: Pre-Re
Hash: 1ac0a4831923f7c02338696d83a009371c28c6ad
Client: 2010-04-20aRagexeRE

If i remember correctly, when party leader leave the party (/leave)
the party will not dismissed, and the settings (exp and items) will be reseted,
But in Herc, your party will be dismissed.

**Comment by kyeme** [comment] 2016-01-16 16:28
I can confirm ~

**Comment by csnv** [comment] 2016-01-16 18:33
But then, who becomes the leader?

**Comment by hemagx** [comment] 2016-01-16 18:38
what's the point of emulate this ?
what's the point of party with no leader?

**Comment by greenboxal** [comment] 2016-01-16 18:42
@hemagx the point is that Hercules should behave exactly as the oficial servers(and options to use other behaviours are always welcomed)

I guess the new leader is either random, or the next in the list

**Comment by csnv** [comment] 2016-01-16 18:45
If we don't have evidence about who becomes the next leader, then we can't emulate it.

**Comment by hemagx** [comment] 2016-01-16 18:46
@greenboxal 
this is not the aim of hercules, maybe it's for rA/eA or any other emulator.
in here the better logic is before emulation, and also emulate bugs or limitation of aegis is not our thing.

@csnv 
next leader, is no one :)

**Comment by MishimaHaruna** [comment] 2016-01-16 18:47
If we have evidence about who the next leader will be, then I'm fine with emulating that... but if the party becomes leader-less (and impossible to further manage), then hell no.

**Comment by Jedzkie** [comment] 2016-01-16 19:21
I will confirm this in kRO since there are many parties there, 3 man party is enough? Or more than?

**Comment by csnv** [comment] 2016-01-16 19:23
I would say it's enough, but it should be repeated several times to confirm if it goes directly to the second party member or if it's random.

**Comment by Jedzkie** [comment] 2016-01-16 19:41
Yeah i will do that.

**Comment by kisuka** [comment] 2016-01-17 00:25
What happens on official:

Tested using 3 users in party. Leader left, No one became leader in the party. The party was then leaderless. Users left in the part could not expel or invite others. Former party leader no longer had a party.

**Comment by AnisotropicDefixation** [comment] 2016-01-17 00:41
It would be a good idea to pass leader to the next player in the list, simply breaking the party can be abused to grief in certan situations, like inside instances, to kick players out.

**Comment by kyeme** [comment] 2016-01-17 00:43
@hemagx 
what's the point of emulate this ?
- For example i accidentally left the party(party leader) the group in the PVP room may not notice that they are already disbanded which may lead to killing each other. Specially if there is a Wizard/Stalker in the party. Devotion will be no use as well

**Comment by csnv** [comment] 2016-01-17 00:46
I support @AnisotropicDefixation idea.

**Comment by hemagx** [comment] 2016-01-17 00:56
@kyeme 
this is bugged behavior and also bad one, moving leader to next is better, but keep party ?
generally the party system in RO is sucks and i wish it was a temporary system.

@AnisotropicDefixation 
i +1 your idea, tho I'm against making any custom systems, but this is a serious good enchants in many ways.

**Comment by kyeme** [comment] 2016-01-17 03:45
@hemagx
For me it is not a bug, it is intended in official server, as you can see from my comment above.
Another explanation for this is, if you happen to chat with party chat then the party leader left the party, it will be public chat and both of you will not be aware that you cannot see each other's chat.
"ohh wtf, did he read my last chat?"

Offtopic: As far as I know the reason why "change party leader" was implemented is to remove hassle from creating new party

**Comment by hemagx** [comment] 2016-01-17 03:49
@kyeme 
not every Aegis thing came cause they just wanted it as it is, you don't know how them guild/party system works and how buggy and hard to manage it is.
it still make no sense to have such kind of party with no leader, it make the name unavailable lot of trash in database for uncleaned parties and many bullshit ~
i'm with @MishimaHaruna  about not doing such thing.

**Comment by kyeme** [comment] 2016-01-17 04:19
Well, Im just giving a point :D :kiss:

**Comment by Jedzkie** [comment] 2016-01-19 04:37
This video will show what is kRO's Party System works if the party creator will leave, the second who joins the party will be the leader.

https://www.youtube.com/watch?v=S4YXMkFTJEc&feature=youtu.be

**Comment by AnisotropicDefixation** [comment] 2016-01-20 03:56
Well, that makes perfect sense.

**Comment by AnisotropicDefixation** [comment] 2016-01-20 03:56
Well, that makes perfect sense.

**Comment by AnisotropicDefixation** [comment] 2016-01-20 03:56
Well, that makes perfect sense.

**Comment by AnisotropicDefixation** [comment] 2016-01-20 03:56
Well, that makes perfect sense.

**Comment by FreddieFatso** [comment] 2016-01-26 06:22
That has to be a bug, because the (still bugged) behaviour on fRO (Renewal) is similar to the old Pre-Renewal behaviour on EuRO:

Party leader leaves -> *NO ONE* is the Party Leader. This renders the party entirely unusable and the name reserved, until the last party member leaves -> party is disbanded automatically and another with the same name can be created. Logging out and back in doesn't change anything, I just tested it with 3 accounts... But I didn't make a video just to prove it is still bugged over there.

The only conclusion, therefore, is that it is a bug kRO has fixed in the meantime, seeing how the European servers were always far behind them in updates. At the very least it isn't an intended behaviour and Hercules should absolutely never emulate such a bug just because AEGIS has it.

Or am I mistaken? I don't think so :P

**Comment by hemagx** [comment] 2016-01-26 06:28
Assigned to self I need some fun after my exams end on 28 ;)

**Comment by hemagx** [comment] 2016-01-26 06:29
Assigned to self I need some fun after my exams end on 28 ;)

**Comment by csnv** [comment] 2016-01-26 18:21
So what is the planned behavior? Will it automatically choose the second member as aparty leader?

**Comment by FreddieFatso** [comment] 2016-01-28 14:36
That's how it looks like in the kRO video.

But might I suggest adding a short grace period before the party leader is granted to someone else? Other MMOs (notably, World of Warcraft) will allow the party leader to retain his or her status for 3-5 minutes and then automatically pass it on to the next party member. That way, a disconnect/relog doesn't change the party structure, but the party won't end up without a leader either.

**Comment by hemagx** [comment] 2016-01-28 14:56
@FreddieFatso
this is only because how them servers and other modern MMO's are not able to be fully sure if player disconnected, anyway and disconnected leader doesn't affect the party in RO cause our system is silly and stupid :)

**Closed** 2017-03-04 19:59 UTC
Labels: component:core, status:code-review, type:enhancement

**Comment by Jedzkie** [comment] 2020-06-25 22:41
@Kenpachi2k13

**Comment by greenboxal** [comment] 2020-06-26 13:55
completely out of topic: this message bump brought me sweet memories lol, I miss those good old times :)

**Comment by Kenpachi2k13** [comment] 2020-07-01 00:50
> This video will show what is kRO's Party System works if the party creator will leave, the second who joins the party will be the leader. the 2nd member must relog to update the check icon, but he/she is automatically become the party leader.
> 
> https://www.youtube.com/watch?v=S4YXMkFTJEc&feature=youtu.be

Will the party lead be passed to that member even if he/she is offline?
I'm asking because we skip offline member when selecting the new leader...
