### ISSUE TITLE
Bard, dance effect time bug

### ISSUE THREAD

**Issue by vnro** [HerculesWS/Hercules#1715] opened 2017-04-25 14:00 UTC
1. Login 2 bard, clown to buff
2. 1st bard Use skill The Apple of Idun
3. 2nd bard use another skill like Assassin Cross of Sunset or something
4. 1st bard use Adaptation to Circumstances first
5. 2nd bard use Adaptation to Circumstances then.
6. U will get bug of The Apple of Idun for 3 mins.

https://youtu.be/mPGpWNeo944

I just tried to use lastest Hercules.

**Comment by Kenpachi2k13** [comment] 2020-05-23 17:20
Duplicate of #1501.
`close();`

**Closed by Kenpachi2k13** 2020-05-23 17:20 UTC
Labels: component:mechanics:skills, severity:2-fair, type:bug
